#!/usr/bin/env node
// After `next build`: writes out/sw.js, the offline helper for the website and installed web app (not used inside
// the iPhone/Android apps, which already carry every file). It keeps a copy of every file of this build on the
// device, so the app opens and moves between screens with no signal; talks and signatures already save on the
// device and upload later (src/lib/outbox.ts). Only this site's own files are kept: Supabase, maps and weather
// requests are never cached here. A new build gets a new cache name and the old copy is removed.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const OUT = path.join(import.meta.dirname, "..", "out");
if (!fs.existsSync(OUT)) throw new Error("out/ is missing: run next build first");
const files = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full);
    else files.push(full);
  }
};
walk(OUT);
const hash = crypto.createHash("sha256");
const urls = [];
for (const f of files.sort()) {
  const rel = "/" + path.relative(OUT, f).split(path.sep).join("/");
  if (rel === "/sw.js" || rel.endsWith(".map")) continue;
  hash.update(rel).update(fs.readFileSync(f));
  // Pages are fetched as /talk/ (trailing slash), not /talk/index.html.
  urls.push(rel.endsWith("/index.html") ? rel.slice(0, -"index.html".length) : rel);
}
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs. Do not edit.
const CACHE = "app-${version}";
const FILES = ${JSON.stringify(urls)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("app-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // Supabase, maps, weather: always the network
  if (req.mode === "navigate") {
    // Pages: the newest from the network when there's signal, this build's copy when there isn't.
    e.respondWith(
      fetch(req).catch(async () => {
        const c = await caches.open(CACHE);
        return (await c.match(url.pathname, { ignoreSearch: true }))
          || (await c.match(url.pathname.replace(/\\/?$/, "/"), { ignoreSearch: true }))
          || (await c.match("/"));
      }),
    );
    return;
  }
  // Scripts, styles, fonts, icons and page data: this build's copy first (file names change with each build).
  e.respondWith(caches.match(req, { ignoreSearch: url.pathname.endsWith(".txt") }).then((hit) => hit || fetch(req)));
});
`;
fs.writeFileSync(path.join(OUT, "sw.js"), sw);
console.log(`out/sw.js: ${urls.length} files, cache app-${version}`);
