// Copies what the tailor-talk server function needs from the app into supabase/functions/_shared/, so the function
// deploys on its own and looks the library talk up itself (never trusting the text a caller sends).
//   npm run functions:sync          (scripts/functions-sync.test.ts fails if the copies are out of date)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { TALKS } from "../src/content/talks";
import { INDUSTRIES } from "../src/core/industries";
import { WORK_SETTINGS } from "../src/core/worksetting";

const root = join(import.meta.dirname, "..");
export const SHARED = join(root, "supabase", "functions", "_shared");

export function libraryJson(): string {
  return JSON.stringify({
    talks: Object.fromEntries(TALKS.map((t) => [t.id, { talk: t.content.en, sources: t.sources.map((s) => s.label) }])),
    industries: Object.fromEntries(INDUSTRIES.map((i) => [i.id, `${i.name}: ${i.sub}`])),
    workSettings: Object.fromEntries(WORK_SETTINGS.map((w) => [w.id, w.name])),
  });
}

export const aiTailorCopy = () =>
  "// GENERATED by scripts/functions-sync.ts from src/core/aiTailor.ts. Do not edit; run npm run functions:sync.\n" +
  readFileSync(join(root, "src", "core", "aiTailor.ts"), "utf8");

if (process.argv[1]?.endsWith("functions-sync.ts")) {
  writeFileSync(join(SHARED, "library.json"), libraryJson());
  writeFileSync(join(SHARED, "aiTailor.ts"), aiTailorCopy());
  console.log("Updated supabase/functions/_shared/library.json and aiTailor.ts");
}
