#!/usr/bin/env node
// End-to-end in real Chromium at phone size: setup -> people/teams via the new admin -> talk with one-at-a-time
// signing (draw on the pad, mark someone absent, undo) -> review -> save -> home status -> records -> admin undo.
import { chromium } from "playwright-core";
import path from "node:path";
import fs from "node:fs";
const __dirname = import.meta.dirname;
const OUT = process.env.OUT || path.join(__dirname, "..", "preview", "dist", "e2e");
fs.mkdirSync(OUT, { recursive: true });
const PAGE = "file://" + path.join(__dirname, "..", "preview", "dist", "index.html");
// Uses CHROMIUM_PATH if set, else Playwright's own Chromium (npx playwright install chromium once).
const launch = () => chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ["--no-sandbox"] });
(async () => {
  const b = await launch();
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: false, colorScheme: process.env.SCHEME || "light" });
  const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
  const log = (...a) => console.log(...a);
  const shot = async (n) => { await p.waitForTimeout(350); await p.screenshot({ path: `${OUT}/e-${n}.png` }); };
  const draw = async () => {
    const c = p.locator("canvas"); await c.scrollIntoViewIfNeeded(); const bb = await c.boundingBox();
    await p.mouse.move(bb.x + 30, bb.y + bb.height * 0.6); await p.mouse.down();
    for (const [dx, dy] of [[80, -40], [140, 30], [200, -30], [260, 20]]) await p.mouse.move(bb.x + dx, bb.y + bb.height * 0.5 + dy, { steps: 4 });
    await p.mouse.up(); await p.waitForTimeout(150);
  };
  await p.goto(PAGE); await p.waitForTimeout(800);
  await p.fill("#co-name", "Demo Roofing"); await p.fill("#co-zip", "33913"); await p.click("text=Create company"); await p.waitForTimeout(900);
  // teams
  await p.click("[role=tab]:has-text('Teams')"); await p.fill('input[aria-label="New team name"]', "Crew 1"); await p.click("text=Add team"); await p.waitForTimeout(400);
  await p.click("[role=tab]:has-text('People')"); await p.waitForTimeout(300);
  const add = async (n, role) => { await p.fill("#np-name", n); await p.selectOption('select[aria-label="Role"]', { label: role }); await p.click("text=Add person"); await p.waitForTimeout(350); };
  await add("Fred Foreman", "Foreman"); await add("Ana Worker", "Crew member"); await add("Ben Worker", "Crew member"); await add("Cal Worker", "Crew member");
  log("toast after add:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  await p.click("text=Done adding"); await p.fill('input[aria-label="Search people"]', "ana"); await p.waitForTimeout(200);
  log("search ana ->", await p.locator("ul li b").allTextContents());
  await p.fill('input[aria-label="Search people"]', ""); await shot("admin-people");
  // edit sheet: open Ben, remove, undo
  await p.click("button:has-text('Ben Worker')"); await p.waitForTimeout(300); await shot("edit-sheet");
  await p.click("text=Remove Ben Worker"); await p.waitForTimeout(400);
  log("after remove:", (await p.locator("ul li b").allTextContents()).join(","), "| toast:", await p.locator("[role=status]").last().textContent());
  await p.click("button:has-text('Undo')"); await p.waitForTimeout(500);
  log("after undo:", (await p.locator("ul li b").allTextContents()).join(","));
  // home -> start talk
  await p.click("nav[aria-label=Main] >> text=Home"); await p.waitForTimeout(700); await shot("home");
  log("getting started:", (await p.locator("text=Getting started").count()) ? await p.locator("section:has-text('Getting started') ol").innerText() : "none");
  await p.click("text=Start this talk"); await p.waitForTimeout(500);
  await p.click("button[aria-label='Bigger text']"); await shot("read");
  await p.click("text=Done reading"); await p.waitForTimeout(400);
  await p.selectOption("#presenter", { index: 1 }); await p.selectOption("#team", { label: "Crew 1" }); await p.waitForTimeout(200);
  await p.click("text=Collect signatures"); await p.waitForTimeout(400); await shot("sign-presenter");
  log("sign 1:", await p.locator("h1").textContent(), "| next disabled:", await p.locator("button:has-text('Next')").isDisabled());
  await draw(); log("next after draw:", await p.locator("button:has-text('Next')").textContent());
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 2:", await p.locator("h1").textContent()); await draw(); await shot("sign-person");
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 3:", await p.locator("h1").textContent());
  await p.click("button:has-text(\"Isn't here\")"); await p.waitForTimeout(300);
  log("after isn't here:", await p.locator("h1").textContent(), "| toast:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  // review
  await p.click("text=Review all").catch(() => {}); await p.waitForTimeout(300); await shot("review");
  log("review:", await p.locator("h1").textContent(), "|", (await p.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await p.click("button:has-text('Save')"); await p.waitForTimeout(1200);
  log("saved:", await p.locator("h1").textContent(), "|", await p.locator("[role=alert]").allInnerTexts()); await shot("after-save");
  await p.click("nav[aria-label=Main] >> text=Home"); await p.waitForTimeout(900); await shot("home-after");
  log("week card:", (await p.locator("section:has-text('Signed this week')").last().innerText().catch(() => "none")).replace(/\s+/g, " "));
  log("last setup:", await p.locator("text=Set up like last time").textContent().catch(() => "none"));
  await p.click("nav[aria-label=Main] >> text=Records"); await p.waitForTimeout(800); await shot("records");
  log("records:", (await p.locator("main h3").allInnerTexts()).join(" | "));
  await p.click("nav[aria-label=Main] >> text=Reports"); await p.waitForTimeout(1000); await shot("reports");
  log("tabs:", (await p.locator("nav[aria-label=Main] a").allInnerTexts()).join(","), "| current:", await p.locator("nav[aria-label=Main] a[aria-current=page]").innerText());
  // Scenario 2: example history -> makeup with "still needs" roster -> record PDF through the preview's save prompt.
  const q = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  q.on("pageerror", (e) => errs.push(e.message));
  await q.addInitScript(() => { window.__saved = null; window.claude = { use: async (n) => n === "downloads" ? { save: async ({ filename, data }) => { window.__saved = { filename, size: data.size }; return { status: "saved" }; } } : null }; });
  await q.goto(PAGE); await q.waitForTimeout(800);
  await q.fill("#co-name", "Demo 2"); await q.click("text=Create company"); await q.waitForTimeout(800);
  await q.click("text=Preview"); await q.click("text=Add example history"); await q.waitForTimeout(1500);
  await q.selectOption("main select", { label: "Example Jobsite" }).catch(() => {}); await q.waitForTimeout(500);
  log("2 home heat:", (await q.locator("main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).find((t) => /Heat index/.test(t)) ?? "none");
  log("2 home week card:", (await q.locator("section:has-text('Signed this week')").last().innerText()).replace(/\s+/g, " "));
  await q.click("text=Give a makeup"); await q.waitForTimeout(600);
  await q.locator("[role=radio]").nth(0).click(); await q.click("button:has-text('Off that week')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  log("2 read heat:", (await q.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await q.locator("main p.border-l-4.border-warn").count());
  await q.screenshot({ path: `${OUT}/e-read-heat.png` });
  await q.click("text=Done reading"); await q.waitForTimeout(300);
  await q.selectOption("#team", "needs"); await q.waitForTimeout(300);
  log("2 still-needs roster:", (await q.locator("main ul li b").allTextContents()).join(", "), "| presenter prefilled:", await q.locator("#presenter").inputValue() !== "");
  if (!(await q.locator("#presenter").inputValue())) await q.selectOption("#presenter", { index: 1 });
  await q.click("text=Collect signatures"); await q.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = q.locator("canvas"); if (!(await c.count())) break;
    const bb = await c.boundingBox(); await q.mouse.move(bb.x + 30, bb.y + 80); await q.mouse.down(); await q.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await q.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await q.mouse.up();
    await q.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await q.waitForTimeout(250);
  }
  log("2 review:", await q.locator("h1").textContent()); await q.click("button:has-text('Save')"); await q.waitForTimeout(1200);
  log("2 saved:", await q.locator("main").innerText().then((t) => t.split("\n").slice(0, 2).join(" | ")));
  await q.click("text=See records"); await q.waitForTimeout(700); await q.locator("main ul li a").first().click(); await q.waitForTimeout(800);
  await q.click("text=Download PDF"); await q.waitForTimeout(2500);
  log("2 pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  await q.click("nav[aria-label=Main] >> text=Reports"); await q.waitForTimeout(1200);
  log("2 reports score:", await q.locator("p.text-6xl").textContent());
  log("2 needs-makeup cards:", (await q.locator("li:has(button:has-text('Give this makeup now'))").allInnerTexts()).map((t) => t.replace(/\s+/g, " ").slice(0, 120)).join(" || "));
  await q.screenshot({ path: `${OUT}/e-reports-top.png`, fullPage: true });
  await q.locator("button:has-text('Give this makeup now')").first().click(); await q.waitForTimeout(700);
  log("2 one-tap makeup:", (await q.locator("[role=radio][aria-checked=true]").innerText()).replace(/\s+/g, " "));
  await q.click("button:has-text('Out sick')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  await q.click("text=Done reading"); await q.waitForTimeout(400);
  log("2 roster ready:", await q.locator("#team").inputValue(), "|", (await q.locator("main ul li b").allTextContents()).join(", "));
  // Scenario 3: spreadsheet import -> talk with site notes, heat reminder and a raised issue -> issue fixed.
  const r = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  r.on("pageerror", (e) => errs.push(e.message));
  await r.goto(PAGE); await r.waitForTimeout(800);
  await r.fill("#co-name", "Demo 3"); await r.click("text=Create company"); await r.waitForTimeout(800);
  await r.click("text=Import from a spreadsheet");
  const csv = "Full Name,Crew,Position,Emp ID,Language\nSam Lead,North Crew,Foreman,2001,English\nRosa Diaz,North Crew,,2002,Spanish\nTom Ng,North Crew,,2003,\n,North Crew,,2004,\n";
  await r.setInputFiles("input[type=file]", { name: "crew.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await r.waitForTimeout(700);
  log("3 import preview:", (await r.locator("[role=dialog] p.tabular-nums").innerText()).replace(/\s+/g, " "), "|", (await r.locator("[role=dialog] [role=status]").first().innerText().catch(() => "")).replace(/\s+/g, " "));
  await r.screenshot({ path: `${OUT}/e-import-preview.png` });
  await r.click("[role=dialog] button:has-text('Import 3 people')"); await r.waitForTimeout(1500);
  log("3 after import:", (await r.locator("main ul li b").allTextContents()).join(", "), "| groups:", (await r.locator("main h2").allTextContents()).join(","));
  await r.click("[role=tab]:has-text('Jobsites')"); await r.fill("#js-name", "Example Jobsite");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(500);
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(900);
  await r.click("text=Check today's heat here").catch(() => {}); await r.waitForTimeout(600);
  log("3 home heat:", (await r.locator("main [role=alert], main [role=status]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).find((t) => /Heat index/.test(t)) ?? "none");
  await r.screenshot({ path: `${OUT}/e-home-heat.png`, fullPage: true });
  await r.click("text=Start this talk"); await r.waitForTimeout(500);
  await r.click("text=+ Add today's site notes"); await r.fill("#site-notes", "Tie off at the ridge anchor");
  log("3 read heat:", (await r.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await r.locator("main p.border-l-4.border-warn").count());
  await r.click("text=Done reading"); await r.waitForTimeout(300);
  await r.selectOption("#presenter", { index: 1 }); await r.selectOption("#team", { label: "North Crew" }); await r.waitForTimeout(200);
  await r.fill('input[aria-label="Add someone not on the roster"]', "Vic Visitor"); await r.fill('input[aria-label="Their company"]', "Example Electric");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(250);
  log("3 walk-in on roster:", (await r.locator("main ul li label").last().innerText()).replace(/\s+/g, " "));
  await r.click("text=Collect signatures"); await r.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = r.locator("canvas"); if (!(await c.count())) break;
    const bb = await c.boundingBox(); await r.mouse.move(bb.x + 30, bb.y + 80); await r.mouse.down(); await r.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await r.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await r.mouse.up();
    await r.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await r.waitForTimeout(250);
  }
  await r.fill('input[aria-label="Add something the crew raised"]', "East ladder rail cracked"); await r.click("form button:has-text('Add')"); await r.waitForTimeout(200);
  log("3 issue owner:", await r.locator('select[aria-label="Owner"] option:checked').innerText(), "| due:", await r.locator('input[aria-label="Fix by"]').inputValue());
  const JPEG = Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAADAAQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCOiiivmj7A/9k=", "base64");
  await r.setInputFiles('input[aria-label="Take a crew photo"]', { name: "crew.jpg", mimeType: "image/jpeg", buffer: JPEG }); await r.waitForTimeout(600);
  log("3 crew photo on review:", await r.locator('img[alt="Crew photo for this talk"]').count(), "| retake/remove:", await r.locator("button:has-text('Retake'), button:has-text('Remove')").count());
  await r.screenshot({ path: `${OUT}/e-review-issue.png`, fullPage: true });
  await r.click("button:has-text('Save')"); await r.waitForTimeout(1200);
  log("3 saved:", (await r.locator("main").innerText()).split("\n").filter((t) => /issue/.test(t)).join(" | "));
  await r.click("text=See records"); await r.waitForTimeout(700);
  await r.locator("main ul li a").first().click(); await r.waitForTimeout(900);
  log("3 record walk-in + photo:", (await r.locator("main").innerText()).split("\n").filter((t) => /Example Electric/.test(t)).join(" | "), "| photo:", await r.locator('img[alt="Crew photo taken at this talk"]').count());
  await r.screenshot({ path: `${OUT}/e-record-photo.png`, fullPage: true });
  log("3 record on site:", (await r.locator("main").innerText()).split("\n").filter((t) => /site|Heat index|ladder/i.test(t)).join(" | "));
  await r.click("nav[aria-label=Main] >> text=Records"); await r.waitForTimeout(600);
  await r.click("[role=tab]:has-text('Issues')"); await r.waitForTimeout(700);
  log("3 issues:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await r.locator("main ul li button").first().click(); await r.waitForTimeout(300);
  await r.fill("#is-note", "Ladder replaced"); await r.click("text=Mark fixed"); await r.waitForTimeout(700);
  await r.click("button:has-text('Fixed (')"); await r.waitForTimeout(300);
  log("3 fixed:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  // Scenario 4: Admin -> Brand. Colors change live, save, survive a reload, and go back to default.
  const brandVar = (pg) => pg.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--brand").trim());
  const markBg = (pg) => pg.evaluate(() => getComputedStyle(document.querySelector("header a span")).backgroundColor);
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500);
  await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(400);
  log("4 brand start:", await brandVar(r), "| checks:", await r.locator("main [role=status]").last().innerText());
  await r.screenshot({ path: `${OUT}/e-brand.png`, fullPage: true });
  await r.click("button:has-text('Harbor')"); await r.waitForTimeout(300);
  log("4 live after Harbor:", await brandVar(r), "| header mark:", await markBg(r));
  await r.fill('input[aria-label="Buttons hex code"]', "#a01539"); await r.press('input[aria-label="Buttons hex code"]', "Enter"); await r.waitForTimeout(300);
  log("4 warning for red buttons:", (await r.locator("main [role=status]").last().innerText()).replace(/\s+/g, " "));
  await r.fill('input[aria-label="Buttons hex code"]', "#D2492F"); await r.press('input[aria-label="Buttons hex code"]', "Enter");
  await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-brand-harbor.png`, fullPage: true });
  await r.reload(); await r.waitForTimeout(1200);
  log("4 after reload:", await brandVar(r));
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-home-harbor.png` });
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(300);
  await r.fill('input[aria-label="Brand hex code"]', "#000000"); await r.press('input[aria-label="Brand hex code"]', "Enter"); await r.waitForTimeout(200);
  await r.click("[role=tab]:has-text('People')"); await r.waitForTimeout(300);
  log("4 unsaved change dropped on leaving:", await brandVar(r));
  await r.click("[role=tab]:has-text('Brand')"); await r.click("button:has-text('Back to default')"); await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  log("4 back to default:", await brandVar(r));
  log("errors:", errs.length ? errs : "none");
  await b.close();
  if (errs.length) process.exit(1);
})().catch((e) => { console.log("E2E ERROR", e.message.split("\n")[0]); process.exit(1); });
