#!/usr/bin/env node
// End-to-end in real Chromium at phone size: setup -> people/teams via the new admin -> talk with one-at-a-time
// signing (draw on the pad, mark someone absent, undo) -> review -> save -> home status -> records -> admin undo.
import { chromium } from "playwright-core";
import path from "node:path";
import fs from "node:fs";
const __dirname = import.meta.dirname;
const OUT = process.env.OUT || path.join(__dirname, "..", "preview", "dist", "e2e");
fs.mkdirSync(OUT, { recursive: true });
const PAGE = "file://" + path.join(__dirname, "..", "preview", "dist", "index.html");
// Uses CHROMIUM_PATH if set, else Playwright's own Chromium (npx playwright install chromium once).
const launch = () => chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ["--no-sandbox"] });
(async () => {
  const b = await launch();
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: false, colorScheme: process.env.SCHEME || "light" });
  const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
  const log = (...a) => console.log(...a);
  const shot = async (n) => { await p.waitForTimeout(350); await p.screenshot({ path: `${OUT}/e-${n}.png` }); };
  const draw = async () => {
    const c = p.locator("canvas"); await c.scrollIntoViewIfNeeded(); const bb = await c.boundingBox();
    await p.mouse.move(bb.x + 30, bb.y + bb.height * 0.6); await p.mouse.down();
    for (const [dx, dy] of [[80, -40], [140, 30], [200, -30], [260, 20]]) await p.mouse.move(bb.x + dx, bb.y + bb.height * 0.5 + dy, { steps: 4 });
    await p.mouse.up(); await p.waitForTimeout(150);
  };
  await p.goto(PAGE); await p.waitForTimeout(800);
  await p.fill("#co-name", "Demo Roofing"); await p.fill("#co-zip", "33913"); await p.click("text=Create company"); await p.waitForTimeout(900);
  // teams
  await p.click("[role=tab]:has-text('Crews')"); await p.fill('input[aria-label="New crew name"]', "Crew 1"); await p.click("text=Add crew"); await p.waitForTimeout(400);
  await p.click("[role=tab]:has-text('People')"); await p.waitForTimeout(300);
  const add = async (n, role) => { await p.fill("#np-name", n); await p.selectOption('select[aria-label="Role"]', { label: role }); await p.click("text=Add person"); await p.waitForTimeout(350); };
  await add("Fred Foreman", "Foreman"); await add("Ana Worker", "Crew member"); await add("Ben Worker", "Crew member"); await add("Cal Worker", "Crew member");
  log("toast after add:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  await p.click("text=Done adding"); await p.fill('input[aria-label="Search people"]', "ana"); await p.waitForTimeout(200);
  log("search ana ->", await p.locator("ul li b").allTextContents());
  await p.fill('input[aria-label="Search people"]', ""); await shot("admin-people");
  // edit sheet: open Ben, remove, undo
  await p.click("button:has-text('Ben Worker')"); await p.waitForTimeout(300); await shot("edit-sheet");
  await p.click("text=Remove Ben Worker"); await p.waitForTimeout(400);
  log("after remove:", (await p.locator("ul li b").allTextContents()).join(","), "| toast:", await p.locator("[role=status]").last().textContent());
  await p.click("button:has-text('Undo')"); await p.waitForTimeout(500);
  log("after undo:", (await p.locator("ul li b").allTextContents()).join(","));
  // home -> start talk
  await p.click("nav[aria-label=Main] >> text=Home"); await p.waitForTimeout(700); await shot("home");
  log("getting started:", (await p.locator("text=Getting started").count()) ? await p.locator("section:has-text('Getting started') ol").innerText() : "none");
  await p.click("text=Start this talk"); await p.waitForTimeout(500);
  await p.click("button[aria-label='Bigger text']"); await shot("read");
  await p.click("text=Done reading"); await p.waitForTimeout(400);
  await p.selectOption("#presenter", { index: 1 }); await p.selectOption("#team", { label: "Crew 1" }); await p.waitForTimeout(200);
  await p.click("text=Collect signatures"); await p.waitForTimeout(400); await shot("sign-presenter");
  log("sign 1:", await p.locator("h1").textContent(), "| next disabled:", await p.locator("main button:has-text('next')").first().isDisabled());
  { const bb = await p.locator("canvas").boundingBox(); await p.mouse.click(bb.x + 100, bb.y + 100); await p.waitForTimeout(200); }
  log("dot rejected:", await p.locator("text=A dot or a tap doesn't count").count() > 0, "| still disabled:", await p.locator("main button:has-text('Sign to continue')").isDisabled());
  await draw(); log("next after draw:", await p.locator("button:has-text('Next')").textContent());
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 2:", await p.locator("h1").textContent());
  // Crew sign only after tapping the signing statement: the pad takes no ink until then.
  await draw(); log("next before statement (pad locked):", await p.locator("button:has-text('Next')").isDisabled());
  await shot("sign-locked");
  await p.click("[role=checkbox]:has-text('I confirm I attended')"); await p.waitForTimeout(150);
  await draw(); log("statement checked:", await p.locator("[role=checkbox]").getAttribute("aria-checked"), "| next enabled:", !(await p.locator("button:has-text('Next')").isDisabled()));
  await shot("sign-person");
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 3:", await p.locator("h1").textContent());
  await p.click("button:has-text(\"Isn't here\")"); await p.waitForTimeout(300);
  log("after isn't here:", await p.locator("h1").textContent(), "| toast:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  // review
  await p.click("text=Review all").catch(() => {}); await p.waitForTimeout(300); await shot("review");
  log("review:", await p.locator("h1").textContent(), "|", (await p.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await p.click("button:has-text('Save')"); await p.waitForTimeout(1200);
  log("saved:", await p.locator("h1").textContent(), "|", await p.locator("[role=alert]").allInnerTexts()); await shot("after-save");
  log("absent toast gone after save:", await p.locator("text=marked absent").count() === 0, "| another crew:", await p.locator("button:has-text('Give it to another crew')").count());
  await p.click("nav[aria-label=Main] >> text=Home"); await p.waitForTimeout(900); await shot("home-after");
  log("week card:", (await p.locator("section:has-text('Signed this week')").last().innerText().catch(() => "none")).replace(/\s+/g, " "));
  log("last setup:", await p.locator("text=Set up like last time").textContent().catch(() => "none"));
  await p.click("nav[aria-label=Main] >> text=Records"); await p.waitForTimeout(800); await shot("records");
  log("records:", (await p.locator("main h3").allInnerTexts()).join(" | "));
  await p.click("nav[aria-label=Main] >> text=Reports"); await p.waitForTimeout(1000); await shot("reports");
  log("tabs:", (await p.locator("nav[aria-label=Main] a").allInnerTexts()).join(","), "| current:", await p.locator("nav[aria-label=Main] a[aria-current=page]").innerText());
  // Scenario 2: example history -> makeup with "still needs" roster -> record PDF through the preview's save prompt.
  const q = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  q.on("pageerror", (e) => errs.push(e.message));
  await q.addInitScript(() => { window.__saved = null; window.claude = { use: async (n) => n === "downloads" ? { save: async ({ filename, data }) => { window.__saved = { filename, size: data.size }; return { status: "saved" }; } } : null }; });
  await q.goto(PAGE); await q.waitForTimeout(800);
  await q.fill("#co-name", "Demo 2"); await q.click("text=Create company"); await q.waitForTimeout(800);
  await q.click("text=Preview"); await q.click("text=Add example history"); await q.waitForTimeout(1500);
  await q.selectOption("main select", { label: "Example Jobsite" }).catch(() => {}); await q.waitForTimeout(500);
  log("2 home weather:", (await q.locator("section[aria-label=\"Jobsite weather\"]").innerText().catch(() => "none")).replace(/\s+/g, " ")); await q.locator("section[aria-label=\"Jobsite weather\"]").screenshot({ path: `${OUT}/e-weather.png` }).catch(() => {});
  log("2 home week card:", (await q.locator("section:has-text('Signed this week')").last().innerText()).replace(/\s+/g, " "));
  await q.click("text=Make up a talk"); await q.waitForTimeout(600);
  await q.locator("[role=radio]").nth(0).click(); await q.click("button:has-text('Off that week')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  log("2 read heat:", (await q.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await q.locator("main p.border-l-4.border-warn").count());
  await q.screenshot({ path: `${OUT}/e-read-heat.png` });
  await q.click("text=Done reading"); await q.waitForTimeout(300);
  await q.selectOption("#team", "needs"); await q.waitForTimeout(300);
  log("2 still-needs roster:", (await q.locator("main ul li b").allTextContents()).join(", "), "| presenter prefilled:", await q.locator("#presenter").inputValue() !== "");
  if (!(await q.locator("#presenter").inputValue())) await q.selectOption("#presenter", { index: 1 });
  await q.click("text=Collect signatures"); await q.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = q.locator("canvas"); if (!(await c.count())) break;
    const box = q.locator("[role=checkbox][aria-checked=false]"); if (await box.count()) await box.click(); // crew tap the statement first
    const bb = await c.boundingBox(); await q.mouse.move(bb.x + 30, bb.y + 80); await q.mouse.down(); await q.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await q.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await q.mouse.up();
    await q.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await q.waitForTimeout(250);
  }
  log("2 review:", await q.locator("h1").textContent()); await q.click("button:has-text('Save')"); await q.waitForTimeout(1200);
  log("2 saved:", await q.locator("main").innerText().then((t) => t.split("\n").slice(0, 2).join(" | ")));
  await q.click("text=See records"); await q.waitForTimeout(700); await q.locator("main ul li a").first().click(); await q.waitForTimeout(800);
  await q.click("text=Download PDF"); await q.waitForTimeout(2500);
  log("2 pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  // Jobsite QR sticker, then "scanning" it: opening the app with ?site=<id> picks that jobsite.
  await q.click("nav[aria-label=Main] >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Jobsites')"); await q.waitForTimeout(400);
  await q.locator("button:has-text('QR sticker')").first().click(); await q.waitForTimeout(1500);
  log("2 qr sticker:", JSON.stringify(await q.evaluate(() => window.__saved)));
  const siteId = await q.evaluate(() => { const d = JSON.parse(localStorage.getItem("tt-preview-db")); return d.jobsites.find((j) => j.active !== false)?.id; });
  await q.evaluate(() => { for (const k of Object.keys(localStorage)) if (k.startsWith("tt-jobsite-")) localStorage.removeItem(k); });
  await q.goto(PAGE + "?site=" + siteId); await q.waitForTimeout(1200);
  log("2 scanned:", await q.locator("text=Jobsite set from the QR sticker").innerText().catch(() => "not set"), "| url cleaned:", !q.url().includes("site="));
  await q.goto(PAGE + "?site=99999999-2222-4333-8444-555555555555"); await q.waitForTimeout(1200);
  log("2 other company's sticker:", await q.locator("text=doesn't have").count() > 0);
  await q.click("nav[aria-label=Main] >> text=Reports"); await q.waitForTimeout(1200);
  log("2 reports score:", await q.locator("p.text-6xl").textContent());
  log("2 needs-makeup cards:", (await q.locator("li:has(button:has-text('Give this makeup now'))").allInnerTexts()).map((t) => t.replace(/\s+/g, " ").slice(0, 120)).join(" || "));
  log("2 reports folded sections:", await q.locator("main details").count(), "| open:", await q.locator("main details[open]").count());
  await q.locator("summary:has-text('By person')").click(); await q.waitForTimeout(200);
  log("2 person cards on phone:", await q.locator("details[open] ul.sm\\:hidden li").count(), "| table hidden:", !(await q.locator("details[open] table").isVisible()));
  await q.screenshot({ path: `${OUT}/e-reports-top.png`, fullPage: true });
  await q.locator("button:has-text('Give this makeup now')").first().click(); await q.waitForTimeout(700);
  log("2 one-tap makeup:", (await q.locator("[role=radio][aria-checked=true]").innerText()).replace(/\s+/g, " "));
  await q.click("button:has-text('Out sick')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  await q.click("text=Done reading"); await q.waitForTimeout(400);
  log("2 roster ready:", await q.locator("#team").inputValue(), "|", (await q.locator("main ul li b").allTextContents()).join(", "));
  // Scenario 3: spreadsheet import -> talk with site notes, heat reminder and a raised issue -> issue fixed.
  const r = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  r.on("pageerror", (e) => errs.push(e.message));
  await r.goto(PAGE); await r.waitForTimeout(800);
  await r.fill("#co-name", "Demo 3"); await r.click("text=Create company"); await r.waitForTimeout(800);
  await r.click("text=Import from a spreadsheet");
  const csv = "Full Name,Crew,Position,Emp ID,Language\nSam Lead,North Crew,Foreman,2001,English\nRosa Diaz,North Crew,,2002,Spanish\nTom Ng,North Crew,,2003,\n,North Crew,,2004,\n";
  await r.setInputFiles("input[type=file]", { name: "crew.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await r.waitForTimeout(700);
  log("3 import preview:", (await r.locator("[role=dialog] p.tabular-nums").innerText()).replace(/\s+/g, " "), "|", (await r.locator("[role=dialog] [role=status]").first().innerText().catch(() => "")).replace(/\s+/g, " "));
  await r.screenshot({ path: `${OUT}/e-import-preview.png` });
  await r.click("[role=dialog] button:has-text('Import 3 people')"); await r.waitForTimeout(1500);
  log("3 after import:", (await r.locator("main ul li b").allTextContents()).join(", "), "| groups:", (await r.locator("main h2").allTextContents()).join(","));
  await r.click("[role=tab]:has-text('Jobsites')"); await r.fill("#js-name", "Example Jobsite");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(500);
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(900);
  await r.click("text=Check the weather here").catch(() => {}); await r.waitForTimeout(600);
  log("3 home heat:", (await r.locator("main [role=alert], main [role=status]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).find((t) => /Heat index/.test(t)) ?? "none");
  await r.screenshot({ path: `${OUT}/e-home-heat.png`, fullPage: true });
  await r.click("text=Start this talk"); await r.waitForTimeout(500);
  await r.click("text=+ Add today's site notes"); await r.fill("#site-notes", "Tie off at the ridge anchor");
  log("3 read heat:", (await r.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await r.locator("main p.border-l-4.border-warn").count());
  await r.click("text=Done reading"); await r.waitForTimeout(300);
  await r.selectOption("#presenter", { index: 1 }); await r.selectOption("#team", { label: "North Crew" }); await r.waitForTimeout(200);
  await r.fill('input[aria-label="Add someone not on the roster"]', "Vic Visitor"); await r.fill('input[aria-label="Their company"]', "Example Electric");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(250);
  log("3 walk-in on roster:", (await r.locator("main ul li label").last().innerText()).replace(/\s+/g, " "));
  await r.click("text=Collect signatures"); await r.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = r.locator("canvas"); if (!(await c.count())) break;
    const box = r.locator("[role=checkbox][aria-checked=false]"); if (await box.count()) await box.click(); // crew tap the statement first
    const bb = await c.boundingBox(); await r.mouse.move(bb.x + 30, bb.y + 80); await r.mouse.down(); await r.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await r.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await r.mouse.up();
    await r.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await r.waitForTimeout(250);
  }
  await r.fill('input[aria-label="Add something the crew raised"]', "East ladder rail cracked"); await r.click("form button:has-text('Add')"); await r.waitForTimeout(200);
  log("3 issue owner:", await r.locator('select[aria-label="Owner"] option:checked').innerText(), "| due:", await r.locator('input[aria-label="Fix by"]').inputValue());
  const JPEG = Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAADAAQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCOiiivmj7A/9k=", "base64");
  await r.setInputFiles('input[aria-label="Take a crew photo"]', { name: "crew.jpg", mimeType: "image/jpeg", buffer: JPEG }); await r.waitForTimeout(600);
  log("3 crew photo on review:", await r.locator('img[alt="Crew photo for this talk"]').count(), "| retake/remove:", await r.locator("button:has-text('Retake'), button:has-text('Remove')").count());
  await r.setInputFiles('input[aria-label="Take a photo of the paper sign-in sheet"]', { name: "sheet.jpg", mimeType: "image/jpeg", buffer: JPEG }); await r.waitForTimeout(600);
  log("3 paper sheet on review:", await r.locator('img[alt="Paper sign-in sheet for this talk"]').count());
  await r.click("text=+ Someone arrived late"); await r.fill("#late-name", "Late Larry"); await r.click("button:has-text('Add and sign')"); await r.waitForTimeout(400);
  log("3 late arrival goes to their turn:", await r.locator("h1").textContent());
  await r.click("text=Review all"); await r.waitForTimeout(300);
  await r.screenshot({ path: `${OUT}/e-review-issue.png`, fullPage: true });
  await r.click("button:has-text('Save')"); await r.waitForTimeout(1200);
  log("3 saved:", (await r.locator("main").innerText()).split("\n").filter((t) => /issue/.test(t)).join(" | "));
  await r.click("text=See records"); await r.waitForTimeout(700);
  await r.locator("main ul li a").first().click(); await r.waitForTimeout(900);
  log("3 record sheet + late arrival:", await r.locator('img[alt="Paper sign-in sheet for this talk"]').count(), "|", (await r.locator("main").innerText()).split("\n").filter((t) => /Late Larry/.test(t)).join(" ").replace(/\s+/g, " "));
  log("3 record walk-in + photo:", (await r.locator("main").innerText()).split("\n").filter((t) => /Example Electric/.test(t)).join(" | "), "| photo:", await r.locator('img[alt="Crew photo taken at this talk"]').count());
  await r.screenshot({ path: `${OUT}/e-record-photo.png`, fullPage: true });
  log("3 record on site:", (await r.locator("main").innerText()).split("\n").filter((t) => /site|Heat index|ladder/i.test(t)).join(" | "));
  await r.click("nav[aria-label=Main] >> text=Records"); await r.waitForTimeout(600);
  await r.click("[role=tab]:has-text('Issues')"); await r.waitForTimeout(700);
  log("3 issues:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await r.locator("main ul li button").first().click(); await r.waitForTimeout(300);
  await r.fill("#is-note", "Ladder replaced"); await r.click("text=Mark fixed"); await r.waitForTimeout(700);
  await r.click("button:has-text('Fixed (')"); await r.waitForTimeout(300);
  log("3 fixed:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  // Scenario 4: Admin -> Brand. Colors change live, save, survive a reload, and go back to default.
  const brandVar = (pg) => pg.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--brand").trim());
  const markBg = (pg) => pg.evaluate(() => getComputedStyle(document.querySelector("header a span")).backgroundColor);
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500);
  await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(400);
  log("4 brand start:", await brandVar(r), "| checks:", await r.locator("main [role=status]").last().innerText());
  await r.screenshot({ path: `${OUT}/e-brand.png`, fullPage: true });
  await r.click("button:has-text('Harbor')"); await r.waitForTimeout(300);
  log("4 live after Harbor:", await brandVar(r), "| header mark:", await markBg(r));
  await r.fill('input[aria-label="Buttons hex code"]', "#a01539"); await r.press('input[aria-label="Buttons hex code"]', "Enter"); await r.waitForTimeout(300);
  log("4 warning for red buttons:", (await r.locator("main [role=status]").last().innerText()).replace(/\s+/g, " "));
  await r.fill('input[aria-label="Buttons hex code"]', "#D2492F"); await r.press('input[aria-label="Buttons hex code"]', "Enter");
  await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-brand-harbor.png`, fullPage: true });
  await r.reload(); await r.waitForTimeout(1200);
  log("4 after reload:", await brandVar(r));
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-home-harbor.png` });
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(300);
  await r.fill('input[aria-label="Brand hex code"]', "#000000"); await r.press('input[aria-label="Brand hex code"]', "Enter"); await r.waitForTimeout(200);
  await r.click("[role=tab]:has-text('People')"); await r.waitForTimeout(300);
  log("4 unsaved change dropped on leaving:", await brandVar(r));
  await r.click("[role=tab]:has-text('Brand')"); await r.click("button:has-text('Back to default')"); await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  log("4 back to default:", await brandVar(r));
  // Scenario 5: Admin -> Talks. Add a talk from another industry, save (starts next week), see it in the Plan, undo.
  await r.click("[role=tab]:has-text('Talks')"); await r.waitForTimeout(400);
  log("5 talks start:", (await r.locator("main span.font-semibold:has-text('picked')").innerText()), "| groups:", (await r.locator("main section h2").allTextContents()).join(", "));
  await r.selectOption('select[aria-label="Show talks for"]', "all"); await r.fill('input[aria-label="Search talks"]', "forklift safety"); await r.waitForTimeout(200);
  await r.locator("main label:has-text('Forklift Safety')").first().click();
  log("5 save button:", await r.locator("main button:has-text('Save')").innerText());
  await r.click("main button:has-text('Save')"); await r.waitForTimeout(700);
  log("5 after save:", (await r.locator("main [role=status], main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await r.screenshot({ path: `${OUT}/e-talks.png`, fullPage: false });
  await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  const weekHas = (label) => r.locator(`main li:has-text("${label}")`).first().locator("option", { hasText: "Forklift Safety" }).count();
  const nextMon = new Date(); nextMon.setDate(nextMon.getDate() - ((nextMon.getDay() + 6) % 7) + 7);
  const nextLabel = nextMon.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  log("5 this week offers it:", await weekHas("This week"), `| week of ${nextLabel} offers it:`, await weekHas(nextLabel));
  await r.click("[role=tab]:has-text('Talks')"); await r.waitForTimeout(400);
  await r.click("main button:has-text('Undo it')"); await r.waitForTimeout(700);
  log("5 after undo:", (await r.locator("main [role=status], main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  // Scenario 6: Admin -> Plan -> How often. Switch to every 4 weeks (starts when this week ends), then keep weekly.
  await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  const cad = r.locator('section[aria-label="How often"]');
  log("6 cadence now:", (await cad.locator("p").first().innerText()).replace(/\s+/g, " "));
  await cad.locator("label:has-text('Every 4 weeks')").click();
  log("6 button:", await cad.locator("button").innerText());
  await cad.locator("button").click(); await r.waitForTimeout(700);
  log("6 after save:", (await r.locator('section[aria-label="How often"]').innerText()).split("\n").filter((l) => /Now:|starts|Changing/.test(l)).join(" | "));
  await r.screenshot({ path: `${OUT}/e-cadence.png`, fullPage: false });
  log("6 plan after:", (await r.locator("main li b").allTextContents()).slice(0, 3).join(" | "));
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(700);
  log("6 home coming up:", (await r.locator("section:has-text('Coming up') li small").allTextContents()).slice(0, 3).join(" | "));
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  await r.locator('section[aria-label="How often"] label:has-text("Every week")').click();
  await r.locator('section[aria-label="How often"] button').click(); await r.waitForTimeout(700);
  log("6 after keep:", (await r.locator('section[aria-label="How often"]').innerText()).split("\n").filter((l) => /Now:|Staying/.test(l)).join(" | "));
  // Scenario 7: Admin -> Safety log. Turn on "Since last talk", log an inspection, catch a name in the crew summary,
  // approve it, see it in the next talk (can't finish reading until it's checked off), add a finding, withdraw.
  await r.click("[role=tab]:has-text('Safety log')"); await r.waitForTimeout(500);
  const slCard = r.locator('section[aria-label="Since last talk"]');
  await slCard.locator("label:has-text('Add it to talks') input").check(); await slCard.locator("button:has-text('Save settings')").click(); await r.waitForTimeout(800);
  await r.click("button:has-text('+ Log')");
  await r.fill("#ev-title", "Weekly scaffold check");
  await r.fill("#ev-f-what", "North scaffold");
  await r.fill("#ev-details", "Found by the site lead. Plank cracked at level 2.");
  const roster = await r.evaluate(() => { const d = JSON.parse(localStorage.getItem("tt-preview-db")); return d.people.map((p) => p.full_name); });
  await r.fill("#ev-summary", `${roster[0]} found a cracked plank on the north scaffold. It was replaced. Check planks before you step on.`);
  log("7 name caught:", (await r.locator("form [role=alert]").innerText().catch(() => "none")).replace(/\s+/g, " ").slice(0, 90));
  await r.fill("#ev-summary", "A cracked plank on the north scaffold was found and replaced. Check planks before you step on.");
  log("7 name problem gone:", await r.locator("form [role=alert]").count() === 0);
  await r.click("form button:has-text('Save')"); await r.waitForTimeout(800);
  const card = r.locator("main li:has-text('Weekly scaffold check')").first();
  log("7 logged:", (await card.innerText()).replace(/\s+/g, " ").slice(0, 100));
  await card.locator("button[aria-expanded]").click(); await r.waitForTimeout(400);
  await card.locator("button:has-text('Approve for talks')").click(); await r.waitForTimeout(800);
  log("7 approved:", (await r.locator("main li:has-text('Weekly scaffold check')").first().innerText()).includes("Approved for talks"));
  await r.screenshot({ path: `${OUT}/e-safetylog.png`, fullPage: false });
  await r.click("nav[aria-label=Main] >> text=Home"); await r.waitForTimeout(700);
  await r.click("button:has-text('Start this talk')"); await r.waitForTimeout(1200);
  log("7 talk section:", (await r.locator("main h3:has-text('Since last talk')").count()) === 1, "|", (await r.locator("main p.text-muted.font-semibold, main p.font-semibold.text-muted").allInnerTexts()).join(" | ").slice(0, 120));
  log("7 done reading blocked:", await r.locator("button:has-text('Check off')").innerText().catch(() => "not blocked"));
  await r.screenshot({ path: `${OUT}/e-sincelast.png`, fullPage: false });
  await r.locator("label:has-text('Reviewed with the crew') input").first().check(); await r.waitForTimeout(300);
  log("7 after check-off:", await r.locator("button:has-text('Done reading')").isEnabled());
  await r.click("text=Discard this talk"); await r.waitForTimeout(200);
  log("7 discard asks first:", await r.locator("button:has-text('Tap again')").innerText().catch(() => "no confirm"));
  await r.click("button:has-text('Tap again')"); await r.waitForTimeout(600);
  await r.click("nav[aria-label=Main] >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Safety log')"); await r.waitForTimeout(600);
  const card2 = r.locator("main li:has-text('Weekly scaffold check')").first();
  await card2.locator("button[aria-expanded]").click(); await r.waitForTimeout(400);
  log("7 approved summary is read-only:", await card2.locator('textarea[aria-label="Crew summary"]').count() === 0);
  await card2.locator('input[aria-label="Finding"]').fill("Replace cracked planks on level 2");
  await card2.locator("button:has-text('Add to issues')").click(); await r.waitForTimeout(700);
  await card2.locator('input[id^="why-"]').fill("Logged for the e2e check");
  await card2.locator("button:has-text('Withdraw')").click(); await card2.locator("button:has-text('Tap again')").click(); await r.waitForTimeout(800);
  log("7 withdrawn:", (await r.locator("main li:has-text('Weekly scaffold check')").first().innerText()).includes("Withdrawn"));
  const issues = await r.evaluate(() => JSON.parse(localStorage.getItem("tt-preview-db")).issues.filter((i) => i.event_id).map((i) => i.description));
  log("7 finding on issues list:", issues.join(", "));
  log("errors:", errs.length ? errs : "none");
  await b.close();
  if (errs.length) process.exit(1);
})().catch((e) => { console.log("E2E ERROR", e.message.split("\n")[0]); process.exit(1); });
