#!/usr/bin/env node
// End-to-end in real Chromium at phone size: setup -> people/teams via the new admin -> talk with one-at-a-time
// signing (draw on the pad, mark someone absent, undo) -> review -> save -> home status -> records -> admin undo.
import { chromium } from "playwright-core";
import path from "node:path";
import fs from "node:fs";
const __dirname = import.meta.dirname;
const OUT = process.env.OUT || path.join(__dirname, "..", "preview", "dist", "e2e");
fs.mkdirSync(OUT, { recursive: true });
const PAGE = "file://" + path.join(__dirname, "..", "preview", "dist", "index.html");
// Uses CHROMIUM_PATH if set, else Playwright's own Chromium (npx playwright install chromium once).
const launch = () => chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, args: ["--no-sandbox"] });
(async () => {
  const b = await launch();
  const p = await b.newPage({ viewport: { width: Number(process.env.VW) || 390, height: Number(process.env.VH) || 844 }, deviceScaleFactor: 2, hasTouch: false, colorScheme: process.env.SCHEME || "light" });
  const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
  const log = (...a) => console.log(...a);
  const shot = async (n) => { await p.waitForTimeout(350); await p.screenshot({ path: `${OUT}/e-${n}.png` }); };
  const draw = async () => {
    const c = p.locator("canvas"); await c.scrollIntoViewIfNeeded(); const bb = await c.boundingBox();
    await p.mouse.move(bb.x + 30, bb.y + bb.height * 0.6); await p.mouse.down();
    for (const [dx, dy] of [[80, -40], [140, 30], [200, -30], [260, 20]]) await p.mouse.move(bb.x + dx, bb.y + bb.height * 0.5 + dy, { steps: 4 });
    await p.mouse.up(); await p.waitForTimeout(150);
  };
  await p.goto(PAGE); await p.waitForTimeout(800);
  await p.fill("#co-name", "Demo Roofing"); await p.fill("#co-zip", "33913"); await p.click("text=Create company"); await p.waitForTimeout(900);
  // teams
  await p.click("[role=tab]:has-text('Teams')"); await p.fill('input[aria-label="New team name"]', "Crew 1"); await p.click("text=Add team"); await p.waitForTimeout(400);
  await p.click("[role=tab]:has-text('People')"); await p.waitForTimeout(300);
  const add = async (n, role) => { await p.fill("#np-name", n); await p.selectOption('select[aria-label="Job title"]', { label: role }); await p.click("text=Add person"); await p.waitForTimeout(350); };
  await add("Fred Foreman", "Foreman"); await add("Ana Worker", "Team member"); await add("Ben Worker", "Team member"); await add("Cal Worker", "Team member");
  log("toast after add:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  await p.click("text=Done adding"); await p.fill('input[aria-label="Search people"]', "ana"); await p.waitForTimeout(200);
  log("search ana ->", await p.locator("ul li b").allTextContents());
  await p.fill('input[aria-label="Search people"]', ""); await shot("admin-people");
  // edit sheet: open Ben, remove, undo
  await p.click("button:has-text('Ben Worker')"); await p.waitForTimeout(300); await shot("edit-sheet");
  await p.click("text=Remove Ben Worker"); await p.waitForTimeout(400);
  log("after remove:", (await p.locator("ul li b").allTextContents()).join(","), "| toast:", await p.locator("[role=status]").last().textContent());
  await p.click("button:has-text('Undo')"); await p.waitForTimeout(500);
  log("after undo:", (await p.locator("ul li b").allTextContents()).join(","));
  // home -> start talk
  await p.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await p.waitForTimeout(700); await shot("home");
  log("getting started:", (await p.locator("text=Getting started").count()) ? await p.locator("section:has-text('Getting started') ol").innerText() : "none");
  await p.click("text=Start this talk"); await p.waitForTimeout(500);
  await p.click("button[aria-label='Bigger text']"); await shot("read");
  await p.click("text=Done reading"); await p.waitForTimeout(400);
  await p.selectOption("#presenter", { index: 1 }); await p.selectOption("#team", { label: "Crew 1" }); await p.waitForTimeout(200);
  await p.click("text=Collect signatures"); await p.waitForTimeout(400); await shot("sign-presenter");
  log("sign 1:", await p.locator("h1").textContent(), "| next disabled:", await p.locator("main button:has-text('next')").first().isDisabled());
  { const bb = await p.locator("canvas").boundingBox(); await p.mouse.click(bb.x + 100, bb.y + 100); await p.waitForTimeout(200); }
  log("dot rejected:", await p.locator("text=A dot or a tap doesn't count").count() > 0, "| still disabled:", await p.locator("main button:has-text('Sign to continue')").isDisabled());
  await draw(); log("next after draw:", await p.locator("button:has-text('Next')").textContent());
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 2:", await p.locator("h1").textContent());
  // Crew sign only after tapping the signing statement: the pad takes no ink until then.
  await draw(); log("next before statement (pad locked):", await p.locator("button:has-text('Next')").isDisabled());
  await shot("sign-locked");
  await p.click("[role=checkbox]:has-text('I confirm I attended')"); await p.waitForTimeout(150);
  await draw(); log("statement checked:", await p.locator("[role=checkbox]").getAttribute("aria-checked"), "| next enabled:", !(await p.locator("button:has-text('Next')").isDisabled()));
  await shot("sign-person");
  await p.click("button:has-text('Next')"); await p.waitForTimeout(300);
  log("sign 3:", await p.locator("h1").textContent());
  await p.click("button:has-text(\"Isn't here\")"); await p.waitForTimeout(300);
  log("after isn't here:", await p.locator("h1").textContent(), "| toast:", await p.locator("[role=status]").last().textContent().catch(() => "-"));
  // review
  await p.click("text=Review all").catch(() => {}); await p.waitForTimeout(300); await shot("review");
  log("review:", await p.locator("h1").textContent(), "|", (await p.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await p.click("button:has-text('Save')"); await p.waitForTimeout(1200);
  log("saved:", await p.locator("h1").textContent(), "|", await p.locator("[role=alert]").allInnerTexts()); await shot("after-save");
  log("absent toast gone after save:", await p.locator("text=marked absent").count() === 0, "| another crew:", await p.locator("button:has-text('Give it to another team')").count());
  await p.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await p.waitForTimeout(900); await shot("home-after");
  log("week card:", (await p.locator("section:has-text('Signed this week')").last().innerText().catch(() => "none")).replace(/\s+/g, " "));
  log("last setup:", await p.locator("text=Set up like last time").textContent().catch(() => "none"));
  await p.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Records"); await p.waitForTimeout(800); await shot("records");
  log("records:", (await p.locator("main h3").allInnerTexts()).join(" | "));
  await p.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await p.waitForTimeout(1000); await shot("reports");
  log("tabs:", (await p.locator("nav[aria-label=Main] a").allInnerTexts()).join(","), "| current:", await p.locator("nav[aria-label=Main] a[aria-current=page]").innerText());
  // Scenario 2: example history -> makeup with "still needs" roster -> record PDF through the preview's save prompt.
  const q = await b.newPage({ viewport: { width: Number(process.env.VW) || 390, height: Number(process.env.VH) || 844 }, deviceScaleFactor: 2, colorScheme: process.env.SCHEME || "light" });
  q.on("pageerror", (e) => errs.push(e.message));
  await q.addInitScript(() => { window.__saved = null; window.claude = { use: async (n) => n === "downloads" ? { save: async ({ filename, data }) => { window.__saved = { filename, size: data.size }; return { status: "saved" }; } } : null }; });
  await q.goto(PAGE); await q.waitForTimeout(800);
  await q.fill("#co-name", "Demo 2"); await q.click("text=Create company"); await q.waitForTimeout(800);
  await q.click("text=Preview"); await q.click("text=Add example history"); await q.waitForTimeout(1500);
  await q.selectOption("main select", { label: "Example Jobsite" }).catch(() => {}); await q.waitForTimeout(500);
  log("2 home weather:", (await q.locator("section[aria-label=\"Jobsite weather\"]").innerText().catch(() => "none")).replace(/\s+/g, " ")); await q.locator("section[aria-label=\"Jobsite weather\"]").screenshot({ path: `${OUT}/e-weather.png` }).catch(() => {});
  // Radar: the 6-hour model forecast is its own loop, labelled as a forecast (run time mocked; no network here).
  const tilePng = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==", "base64");
  await q.route("**/tile.openstreetmap.org/**", (route) => route.fulfill({ contentType: "image/png", body: tilePng }));
  await q.route("**/tile.py/**", (route) => route.fulfill({ contentType: "image/png", body: tilePng }));
  await q.route("**/hrrr/refd_1080.json", (route) => route.fulfill({ contentType: "application/json", body: JSON.stringify({ model_init_utc: new Date(Date.now() - 2 * 3600e3).toISOString().slice(0, 13) + ":00:00Z" }) }));
  await q.click("text=Show radar").catch(() => {}); await q.waitForTimeout(400);
  await q.click("button:has-text('Next 6h')"); await q.waitForTimeout(800);
  log("2 forecast banner:", await q.locator("text=Model forecast, not radar").count() > 0, "| tiles:", (await q.locator("img[src*='hrrr::REFD-F']").first().getAttribute("src").catch(() => "none"))?.replace(/\/\d+\/\d+\/\d+\.png$/, ""));
  await q.locator("section[aria-label=\"Jobsite weather\"]").screenshot({ path: `${OUT}/e-forecast.png` }).catch(() => {});
  log("2 home week card:", (await q.locator("section:has-text('Signed this week')").last().innerText()).replace(/\s+/g, " "));
  await q.click("text=Make up a talk"); await q.waitForTimeout(600);
  await q.locator("[role=radio]").nth(0).click(); await q.click("button:has-text('Off that week')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  log("2 read heat:", (await q.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await q.locator("main p.border-l-4.border-warn").count());
  await q.screenshot({ path: `${OUT}/e-read-heat.png` });
  await q.click("text=Done reading"); await q.waitForTimeout(300);
  await q.selectOption("#team", "needs"); await q.waitForTimeout(300);
  log("2 still-needs roster:", (await q.locator("main ul li b").allTextContents()).join(", "), "| presenter prefilled:", await q.locator("#presenter").inputValue() !== "");
  if (!(await q.locator("#presenter").inputValue())) await q.selectOption("#presenter", { index: 1 });
  await q.click("text=Collect signatures"); await q.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = q.locator("canvas"); if (!(await c.count())) break;
    const box = q.locator("[role=checkbox][aria-checked=false]"); if (await box.count()) await box.click(); // crew tap the statement first
    const bb = await c.boundingBox(); await q.mouse.move(bb.x + 30, bb.y + 80); await q.mouse.down(); await q.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await q.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await q.mouse.up();
    await q.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await q.waitForTimeout(250);
  }
  log("2 review:", await q.locator("h1").textContent()); await q.click("button:has-text('Save')"); await q.waitForTimeout(1200);
  log("2 saved:", await q.locator("main").innerText().then((t) => t.split("\n").slice(0, 2).join(" | ")));
  await q.click("text=See records"); await q.waitForTimeout(700); await q.locator("main ul li a").first().click(); await q.waitForTimeout(800);
  await q.click("text=Download PDF"); await q.waitForTimeout(2500);
  log("2 pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  // Jobsite QR sticker, then "scanning" it: opening the app with ?site=<id> picks that jobsite.
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Jobsites')"); await q.waitForTimeout(400);
  await q.locator("button:has-text('QR sticker')").first().click(); await q.waitForTimeout(1500);
  log("2 qr sticker:", JSON.stringify(await q.evaluate(() => window.__saved)));
  const siteId = await q.evaluate(() => { const d = JSON.parse(localStorage.getItem("tt-preview-db")); return d.jobsites.find((j) => j.active !== false)?.id; });
  await q.evaluate(() => { for (const k of Object.keys(localStorage)) if (k.startsWith("tt-jobsite-")) localStorage.removeItem(k); });
  await q.goto(PAGE + "?site=" + siteId); await q.waitForTimeout(1200);
  log("2 scanned:", await q.locator("text=Jobsite set from the QR sticker").innerText().catch(() => "not set"), "| url cleaned:", !q.url().includes("site="));
  await q.goto(PAGE + "?site=99999999-2222-4333-8444-555555555555"); await q.waitForTimeout(1200);
  log("2 other company's sticker:", await q.locator("text=doesn't have").count() > 0);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(1200);
  log("2 reports score:", await q.locator("p:has-text('Sign-in rate') + p").first().textContent());
  log("2 needs-makeup cards:", (await q.locator("li:has(button:has-text('Give this makeup now'))").allInnerTexts()).map((t) => t.replace(/\s+/g, " ").slice(0, 120)).join(" || "));
  log("2 reports folded sections:", await q.locator("main details").count(), "| open:", await q.locator("main details[open]").count());
  await q.locator("summary:has-text('By person')").click(); await q.waitForTimeout(200);
  log("2 person cards on phone:", await q.locator("details[open] ul.sm\\:hidden li").count(), "| table hidden:", !(await q.locator("details[open] table").isVisible()));
  await q.screenshot({ path: `${OUT}/e-reports-top.png`, fullPage: true });
  await q.locator("button:has-text('Give this makeup now')").first().click(); await q.waitForTimeout(700);
  log("2 one-tap makeup:", (await q.locator("[role=radio][aria-checked=true]").innerText()).replace(/\s+/g, " "));
  await q.click("button:has-text('Out sick')"); await q.click("text=Continue to the talk"); await q.waitForTimeout(400);
  await q.click("text=Done reading"); await q.waitForTimeout(400);
  log("2 roster ready:", await q.locator("#team").inputValue(), "|", (await q.locator("main ul li b").allTextContents()).join(", "));
  // Scenario 3: spreadsheet import -> talk with site notes, heat reminder and a raised issue -> issue fixed.
  const r = await b.newPage({ viewport: { width: Number(process.env.VW) || 390, height: Number(process.env.VH) || 844 }, deviceScaleFactor: 2, colorScheme: process.env.SCHEME || "light" });
  r.on("pageerror", (e) => errs.push(e.message));
  await r.goto(PAGE); await r.waitForTimeout(800);
  await r.fill("#co-name", "Demo 3"); await r.click("text=Create company"); await r.waitForTimeout(800);
  await r.click("text=Import from a spreadsheet");
  const csv = "Full Name,Crew,Position,Emp ID,Language\nSam Lead,North Crew,Foreman,2001,English\nRosa Diaz,North Crew,,2002,Spanish\nTom Ng,North Crew,,2003,\n,North Crew,,2004,\n";
  await r.setInputFiles("input[type=file]", { name: "crew.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await r.waitForTimeout(700);
  log("3 import preview:", (await r.locator("[role=dialog] p.tabular-nums").innerText()).replace(/\s+/g, " "), "|", (await r.locator("[role=dialog] [role=status]").first().innerText().catch(() => "")).replace(/\s+/g, " "));
  await r.screenshot({ path: `${OUT}/e-import-preview.png` });
  await r.click("[role=dialog] button:has-text('Import 3 people')"); await r.waitForTimeout(1500);
  log("3 after import:", (await r.locator("main ul li b").allTextContents()).join(", "), "| groups:", (await r.locator("main h2").allTextContents()).join(","));
  await r.click("[role=tab]:has-text('Jobsites')"); await r.fill("#js-name", "Example Jobsite");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(500);
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(900);
  await r.click("text=Check the weather here").catch(() => {}); await r.waitForTimeout(600);
  log("3 home heat:", (await r.locator("main [role=alert], main [role=status]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).find((t) => /Heat index/.test(t)) ?? "none");
  await r.screenshot({ path: `${OUT}/e-home-heat.png`, fullPage: true });
  await r.click("text=Start this talk"); await r.waitForTimeout(500);
  await r.click("text=+ Add today's site notes"); await r.fill("#site-notes", "Tie off at the ridge anchor");
  log("3 read heat:", (await r.locator("main p.border-warn").first().innerText().catch(() => "none")).replace(/\s+/g, " "), "| reminder lines:", await r.locator("main p.border-l-4.border-warn").count());
  await r.click("text=Done reading"); await r.waitForTimeout(300);
  await r.selectOption("#presenter", { index: 1 }); await r.selectOption("#team", { label: "North Crew" }); await r.waitForTimeout(200);
  await r.fill('input[aria-label="Add someone not on the roster"]', "Vic Visitor"); await r.fill('input[aria-label="Their company"]', "Example Electric");
  await r.click("form button:has-text('Add')"); await r.waitForTimeout(250);
  log("3 walk-in on roster:", (await r.locator("main ul li label").last().innerText()).replace(/\s+/g, " "));
  await r.click("text=Collect signatures"); await r.waitForTimeout(300);
  for (let i = 0; i < 6; i++) {
    const c = r.locator("canvas"); if (!(await c.count())) break;
    const box = r.locator("[role=checkbox][aria-checked=false]"); if (await box.count()) await box.click(); // crew tap the statement first
    const bb = await c.boundingBox(); await r.mouse.move(bb.x + 30, bb.y + 80); await r.mouse.down(); await r.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await r.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await r.mouse.up();
    await r.locator("button:has-text('Next'), button:has-text('Done signing')").first().click(); await r.waitForTimeout(250);
  }
  await r.fill('input[aria-label="Add something the team raised"]', "East ladder rail cracked"); await r.click("form button:has-text('Add')"); await r.waitForTimeout(200);
  log("3 issue owner:", await r.locator('select[aria-label="Owner"] option:checked').innerText(), "| due:", await r.locator('input[aria-label="Fix by"]').inputValue());
  const JPEG = Buffer.from("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAADAAQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCOiiivmj7A/9k=", "base64");
  await r.setInputFiles('input[aria-label="Take a team photo"]', { name: "crew.jpg", mimeType: "image/jpeg", buffer: JPEG }); await r.waitForTimeout(600);
  log("3 crew photo on review:", await r.locator('img[alt="Team photo for this talk"]').count(), "| retake/remove:", await r.locator("button:has-text('Retake'), button:has-text('Remove')").count());
  await r.setInputFiles('input[aria-label="Take a photo of the paper sign-in sheet"]', { name: "sheet.jpg", mimeType: "image/jpeg", buffer: JPEG }); await r.waitForTimeout(600);
  log("3 paper sheet on review:", await r.locator('img[alt="Paper sign-in sheet for this talk"]').count());
  await r.click("text=+ Someone arrived late"); await r.fill("#late-name", "Late Larry"); await r.click("button:has-text('Add and sign')"); await r.waitForTimeout(400);
  log("3 late arrival goes to their turn:", await r.locator("h1").textContent());
  await r.click("text=Review all"); await r.waitForTimeout(300);
  await r.screenshot({ path: `${OUT}/e-review-issue.png`, fullPage: true });
  await r.click("button:has-text('Save')"); await r.waitForTimeout(1200);
  log("3 saved:", (await r.locator("main").innerText()).split("\n").filter((t) => /issue/.test(t)).join(" | "));
  await r.click("text=See records"); await r.waitForTimeout(700);
  await r.locator("main ul li a").first().click(); await r.waitForTimeout(900);
  log("3 record sheet + late arrival:", await r.locator('img[alt="Paper sign-in sheet for this talk"]').count(), "|", (await r.locator("main").innerText()).split("\n").filter((t) => /Late Larry/.test(t)).join(" ").replace(/\s+/g, " "));
  log("3 record walk-in + photo:", (await r.locator("main").innerText()).split("\n").filter((t) => /Example Electric/.test(t)).join(" | "), "| photo:", await r.locator('img[alt="Team photo taken at this talk"]').count());
  await r.screenshot({ path: `${OUT}/e-record-photo.png`, fullPage: true });
  log("3 record on site:", (await r.locator("main").innerText()).split("\n").filter((t) => /site|Heat index|ladder/i.test(t)).join(" | "));
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Records"); await r.waitForTimeout(600);
  await r.click("[role=tab]:has-text('Issues')"); await r.waitForTimeout(700);
  log("3 issues:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await r.locator("main ul li button").first().click(); await r.waitForTimeout(300);
  await r.fill("#is-note", "Ladder replaced"); await r.click("text=Mark fixed"); await r.waitForTimeout(700);
  await r.click("button:has-text('Fixed (')"); await r.waitForTimeout(300);
  log("3 fixed:", (await r.locator("main ul li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  // Scenario 4: Admin -> Brand. Colors change live, save, survive a reload, and go back to default.
  const brandVar = (pg) => pg.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue("--brand").trim());
  const markBg = (pg) => pg.evaluate(() => getComputedStyle(document.querySelector("header a span")).backgroundColor);
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await r.waitForTimeout(500);
  await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(400);
  log("4 brand start:", await brandVar(r), "| checks:", await r.locator("main [role=status]").last().innerText());
  await r.screenshot({ path: `${OUT}/e-brand.png`, fullPage: true });
  await r.click("button:has-text('Harbor')"); await r.waitForTimeout(300);
  log("4 live after Harbor:", await brandVar(r), "| header mark:", await markBg(r));
  await r.fill('input[aria-label="Buttons hex code"]', "#a01539"); await r.press('input[aria-label="Buttons hex code"]', "Enter"); await r.waitForTimeout(300);
  log("4 warning for red buttons:", (await r.locator("main [role=status]").last().innerText()).replace(/\s+/g, " "));
  await r.fill('input[aria-label="Buttons hex code"]', "#D2492F"); await r.press('input[aria-label="Buttons hex code"]', "Enter");
  await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-brand-harbor.png`, fullPage: true });
  await r.reload(); await r.waitForTimeout(1200);
  log("4 after reload:", await brandVar(r));
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(700);
  await r.screenshot({ path: `${OUT}/e-home-harbor.png` });
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Brand')"); await r.waitForTimeout(300);
  await r.fill('input[aria-label="Brand hex code"]', "#000000"); await r.press('input[aria-label="Brand hex code"]', "Enter"); await r.waitForTimeout(200);
  await r.click("[role=tab]:has-text('People')"); await r.waitForTimeout(300);
  log("4 unsaved change dropped on leaving:", await brandVar(r));
  await r.click("[role=tab]:has-text('Brand')"); await r.click("button:has-text('Back to default')"); await r.click("button:has-text('Save colors')"); await r.waitForTimeout(700);
  log("4 back to default:", await brandVar(r));
  // Scenario 5: Admin -> Talks. Add a talk from another industry, save (starts next week), see it in the Plan, undo.
  await r.click("[role=tab]:has-text('Talks')"); await r.waitForTimeout(400);
  log("5 talks start:", (await r.locator("main span.font-semibold:has-text('picked')").innerText()), "| groups:", (await r.locator("main section h2").allTextContents()).join(", "));
  await r.selectOption('select[aria-label="Show talks for"]', "all"); await r.fill('input[aria-label="Search talks"]', "forklift safety"); await r.waitForTimeout(200);
  await r.locator("main label:has-text('Forklift Safety')").first().click();
  log("5 save button:", await r.locator("main button:has-text('Save')").innerText());
  await r.click("main button:has-text('Save')"); await r.waitForTimeout(700);
  log("5 after save:", (await r.locator("main [role=status], main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  await r.screenshot({ path: `${OUT}/e-talks.png`, fullPage: false });
  await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  const weekHas = (label) => r.locator(`main li:has-text("${label}")`).first().locator("option", { hasText: "Forklift Safety" }).count();
  const nextMon = new Date(); nextMon.setDate(nextMon.getDate() - ((nextMon.getDay() + 6) % 7) + 7);
  const nextLabel = nextMon.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  log("5 this week offers it:", await weekHas("This week"), `| week of ${nextLabel} offers it:`, await weekHas(nextLabel));
  await r.click("[role=tab]:has-text('Talks')"); await r.waitForTimeout(400);
  await r.click("main button:has-text('Undo it')"); await r.waitForTimeout(700);
  log("5 after undo:", (await r.locator("main [role=status], main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  // Scenario 6: Admin -> Plan -> How often. Switch to every 4 weeks (starts when this week ends), then keep weekly.
  await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  const cad = r.locator('section[aria-label="How often"]');
  log("6 cadence now:", (await cad.locator("p").first().innerText()).replace(/\s+/g, " "));
  await cad.locator("label:has-text('Every 4 weeks')").click();
  log("6 button:", await cad.locator("button").innerText());
  await cad.locator("button").click(); await r.waitForTimeout(700);
  log("6 after save:", (await r.locator('section[aria-label="How often"]').innerText()).split("\n").filter((l) => /Now:|starts|Changing/.test(l)).join(" | "));
  await r.screenshot({ path: `${OUT}/e-cadence.png`, fullPage: false });
  log("6 plan after:", (await r.locator("main li b").allTextContents()).slice(0, 3).join(" | "));
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(700);
  log("6 home coming up:", (await r.locator("section:has-text('Coming up') li small").allTextContents()).slice(0, 3).join(" | "));
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Plan')"); await r.waitForTimeout(500);
  await r.locator('section[aria-label="How often"] label:has-text("Every week")').click();
  await r.locator('section[aria-label="How often"] button').click(); await r.waitForTimeout(700);
  log("6 after keep:", (await r.locator('section[aria-label="How often"]').innerText()).split("\n").filter((l) => /Now:|Staying/.test(l)).join(" | "));
  // Repeat talks: respirators every 3 months, with the rule's own reminder (a talk is a refresher, not the training).
  const rep = r.locator('section[aria-label="Repeat talks"]');
  await rep.locator('select[aria-label="Talk to repeat"]').selectOption("respirators"); await r.waitForTimeout(150);
  await rep.locator("button[role=radio]:has-text('Every 3 months')").click();
  log("6 repeat note:", (await rep.locator("[role=status]").first().innerText().catch(() => "none")).replace(/\s+/g, " ").slice(0, 160));
  await rep.locator("button:has-text('Add repeat')").click(); await r.waitForTimeout(700);
  log("6 repeat saved:", (await rep.locator("li").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" || "));
  const plannedResp = await r.locator("main ul li:has-text('Respirators')").count();
  log("6 respirators in the plan list:", plannedResp > 0);
  // Scenario 7: Admin -> Safety log. Turn on "Since last talk", log an inspection, catch a name in the crew summary,
  // approve it, see it in the next talk (can't finish reading until it's checked off), add a finding, withdraw.
  await r.click("[role=tab]:has-text('Safety log')"); await r.waitForTimeout(500);
  const slCard = r.locator('section[aria-label="Since last talk"]');
  await slCard.locator("label:has-text('Add it to talks') input").check(); await slCard.locator("button:has-text('Save settings')").click(); await r.waitForTimeout(800);
  await r.click("button:has-text('+ Log')");
  await r.fill("#ev-title", "Weekly scaffold check");
  await r.fill("#ev-f-what", "North scaffold");
  await r.fill("#ev-details", "Found by the site lead. Plank cracked at level 2.");
  const roster = await r.evaluate(() => { const d = JSON.parse(localStorage.getItem("tt-preview-db")); return d.people.map((p) => p.full_name); });
  await r.fill("#ev-summary", `${roster[0]} found a cracked plank on the north scaffold. It was replaced. Check planks before you step on.`);
  log("7 name caught:", (await r.locator("form [role=alert]").innerText().catch(() => "none")).replace(/\s+/g, " ").slice(0, 90));
  await r.fill("#ev-summary", "A cracked plank on the north scaffold was found and replaced. Check planks before you step on.");
  log("7 name problem gone:", await r.locator("form [role=alert]").count() === 0);
  await r.click("form button:has-text('Save')"); await r.waitForTimeout(800);
  const card = r.locator("main li:has-text('Weekly scaffold check')").first();
  log("7 logged:", (await card.innerText()).replace(/\s+/g, " ").slice(0, 100));
  await card.locator("button[aria-expanded]").click(); await r.waitForTimeout(400);
  await card.locator("button:has-text('Approve for talks')").click(); await r.waitForTimeout(800);
  log("7 approved:", (await r.locator("main li:has-text('Weekly scaffold check')").first().innerText()).includes("Approved for talks"));
  await r.screenshot({ path: `${OUT}/e-safetylog.png`, fullPage: false });
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(700);
  await r.click("button:has-text('Start this talk')"); await r.waitForTimeout(1200);
  log("7 talk section:", (await r.locator("main h3:has-text('Since last talk')").count()) === 1, "|", (await r.locator("main p.text-muted.font-semibold, main p.font-semibold.text-muted").allInnerTexts()).join(" | ").slice(0, 120));
  log("7 done reading blocked:", await r.locator("button:has-text('Check off')").innerText().catch(() => "not blocked"));
  await r.screenshot({ path: `${OUT}/e-sincelast.png`, fullPage: false });
  await r.locator("label:has-text('Reviewed with the team') input").first().check(); await r.waitForTimeout(300);
  log("7 after check-off:", await r.locator("button:has-text('Done reading')").isEnabled());
  await r.click("text=Discard this talk"); await r.waitForTimeout(200);
  log("7 discard asks first:", await r.locator("button:has-text('Tap again')").innerText().catch(() => "no confirm"));
  await r.click("button:has-text('Tap again')"); await r.waitForTimeout(600);
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Safety log')"); await r.waitForTimeout(600);
  const card2 = r.locator("main li:has-text('Weekly scaffold check')").first();
  await card2.locator("button[aria-expanded]").click(); await r.waitForTimeout(400);
  log("7 approved summary is read-only:", await card2.locator('textarea[aria-label="Team summary"]').count() === 0);
  await card2.locator('input[aria-label="Finding"]').fill("Replace cracked planks on level 2");
  await card2.locator("button:has-text('Add to issues')").click(); await r.waitForTimeout(700);
  await card2.locator('input[id^="why-"]').fill("Logged for the e2e check");
  await card2.locator("button:has-text('Withdraw')").click(); await card2.locator("button:has-text('Tap again')").click(); await r.waitForTimeout(800);
  log("7 withdrawn:", (await r.locator("main li:has-text('Weekly scaffold check')").first().innerText()).includes("Withdrawn"));
  const issues = await r.evaluate(() => JSON.parse(localStorage.getItem("tt-preview-db")).issues.filter((i) => i.event_id).map((i) => i.description));
  log("7 finding on issues list:", issues.join(", "));
  // Scenario 8: daily pre-task plan. Turn it on, plan the day, crew signs, saved as its own record that never counts
  // toward the weekly talk.
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(800);
  const weekBefore = (await r.locator("section:has-text('signed this week')").last().innerText().catch(() => "none")).replace(/\s+/g, " ");
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await r.waitForTimeout(500); await r.click("[role=tab]:has-text('Company')"); await r.waitForTimeout(400);
  await r.locator("label:has-text('Daily pre-task plans') input").check(); await r.waitForTimeout(600);
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await r.waitForTimeout(800);
  await r.click("text=Start today's pre-task plan"); await r.waitForTimeout(600);
  log("8 plan step:", await r.locator("h1").textContent());
  await r.click("button:has-text(\"Who's here\")"); await r.waitForTimeout(200);
  log("8 needs a plan first:", (await r.locator("[role=alert]").innerText().catch(() => "none")).replace(/\s+/g, " "));
  await r.fill('input[aria-label="Add a task"]', "Tear off the north slope"); await r.click("form >> button:has-text('Add')");
  await r.click("text=Pick from common hazards"); await r.click("button:has-text('+ Falls from an edge')");
  await r.click("button[aria-pressed]:has-text('Hard hat')");
  await r.locator("li:has-text('Scaffold') input[type=checkbox]").check(); await r.waitForTimeout(150);
  log("8 scaffold reminder:", (await r.locator("li:has-text('Scaffold') p").first().innerText()).replace(/\s+/g, " "));
  await r.fill('input[aria-label="Who checked the scaffold"]', "Sam Lead");
  await r.fill("#pt-muster", "Front gate");
  await r.screenshot({ path: `${OUT}/e-daily-plan.png`, fullPage: true });
  await r.click("button:has-text(\"Who's here\")"); await r.waitForTimeout(400);
  await r.selectOption("#presenter", { index: 1 }); await r.selectOption("#team", { label: "North Crew" }); await r.waitForTimeout(200);
  log("8 no 'still needs' option:", (await r.locator("#team option[value=needs]").count()) === 0);
  await r.click("text=Collect signatures"); await r.waitForTimeout(400);
  { const c = r.locator("canvas"); const bb = await c.boundingBox(); await r.mouse.move(bb.x + 30, bb.y + 80); await r.mouse.down(); await r.mouse.move(bb.x + 150, bb.y + 40, { steps: 5 }); await r.mouse.move(bb.x + 250, bb.y + 90, { steps: 5 }); await r.mouse.up(); }
  await r.click("button:has-text('Next')"); await r.waitForTimeout(300);
  log("8 crew statement:", (await r.locator("[role=checkbox]").innerText()).replace(/\s+/g, " ").slice(0, 80));
  await r.click("text=Review all"); await r.waitForTimeout(300);
  await r.click("button:has-text('Save')"); await r.waitForTimeout(1200);
  log("8 saved:", await r.locator("h1").textContent());
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home").catch(() => {}); await r.waitForTimeout(800);
  if (!(await r.locator("nav[aria-label=Main]").count())) { await r.click("text=Home"); await r.waitForTimeout(800); }
  const weekAfter = (await r.locator("section:has-text('signed this week')").last().innerText().catch(() => "none")).replace(/\s+/g, " ");
  log("8 weekly count unchanged:", weekBefore === weekAfter, "|", weekAfter.slice(0, 60));
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Records"); await r.waitForTimeout(700);
  log("8 records tag:", await r.locator("main li:has-text('Daily plan')").count() > 0);
  await r.locator("main li:has-text('Daily plan') a").first().click(); await r.waitForTimeout(900);
  log("8 record:", (await r.locator("main p").first().innerText()).replace(/\s+/g, " "), "|", (await r.locator("main").innerText()).includes("Equipment reminders"));
  await r.screenshot({ path: `${OUT}/e-daily-record.png`, fullPage: true });
  await r.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await r.waitForTimeout(1000);
  log("8 reports daily:", (await r.locator("summary:has-text('Daily pre-task plans')").innerText().catch(() => "none")).replace(/\s+/g, " "));
  // Scenario 9: safety profile (company with example history). Add a self-reported EMR, check the honest missed-weeks
  // count and program elements, then download the renewal packet through the preview's save prompt.
  await q.goto(PAGE); await q.waitForTimeout(1200); // page q was left mid-talk by an earlier scenario
  log("9 home streak:", (await q.locator("section[aria-label^='This']").innerText().catch(() => "none")).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-home-streak.png` });
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(1000);
  await q.locator("a[href*='profile']").first().click(); await q.waitForTimeout(1500);
  log("9 profile:", await q.locator("h1").textContent(), "| figures:", (await q.locator("main dl").innerText()).replace(/\s+/g, " ").slice(0, 160));
  log("9 missed weeks notice:", (await q.locator("text=Weeks with no talk recorded").count()) > 0 ? "shown" : "none (no missed weeks)");
  log("9 elements:", (await q.locator("main ul li b").allInnerTexts()).slice(0, 7).join(" | "));
  await q.fill("#emr-year", "2026"); await q.fill("#emr-value", "0.87"); await q.click("button:has-text('Save EMR')"); await q.waitForTimeout(800);
  log("9 emr:", (await q.locator("section[aria-label='Experience mod']").innerText()).includes("2026: 0.87"));
  await q.screenshot({ path: `${OUT}/e-profile.png`, fullPage: true });
  await q.evaluate(() => { window.__saved = null; });
  await q.click("text=Download renewal packet"); await q.waitForTimeout(2500);
  log("9 renewal pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  log("9 no compliance claim:", !/\bcompliant\b/i.test((await q.locator("main").innerText()).replace("doesn't certify compliance", "")));
  // Scenario 10: job titles, app access, and each app role's view (preview "View as").
  await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Job titles')"); await q.waitForTimeout(400);
  log("10 titles:", await q.locator("main ul li").count(), "| Laborer gives talks:", await q.locator('input[aria-label="Laborer gives talks"]').isChecked().catch(() => "missing"),
    "| Foreman gives talks:", await q.locator('input[aria-label="Foreman gives talks"]').isChecked().catch(() => "missing"), "| starter offer:", await q.locator("text=Starter titles for").count());
  await q.screenshot({ path: `${OUT}/e-job-titles.png`, fullPage: true });
  await q.click("[role=tab]:has-text('App access')"); await q.waitForTimeout(500);
  await q.fill("#inv-email", "office@example.com"); await q.selectOption("#inv-role", "office"); await q.click("button:has-text('Send invite')"); await q.waitForTimeout(500);
  await q.selectOption("#inv-role", "employee");
  log("10 invite waiting:", (await q.locator("li:has-text('office@example.com')").innerText().catch(() => "none")).replace(/\s+/g, " "), "| employee needs a roster person:", await q.locator("button:has-text('Send invite')").isDisabled());
  await q.screenshot({ path: `${OUT}/e-app-access.png`, fullPage: true });
  const viewAs = async (role) => { await q.click("button[aria-label='Show preview options']").catch(() => {}); await q.selectOption('select[aria-label="View as"]', role); await q.waitForTimeout(1500); };
  await viewAs("office");
  log("10 office tabs:", (await q.locator("nav[aria-label=Main] a").allInnerTexts()).join(","), "| start talk shown:", await q.locator("button:has-text('Start this talk')").count());
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(1000);
  log("10 office reports:", await q.locator("h1").first().textContent(), "| profile link:", await q.locator("a[href*='profile']").count(), "| makeup buttons:", await q.locator("button:has-text('Give this makeup now')").count());
  await viewAs("employee");
  log("10 employee tabs:", (await q.locator("nav[aria-label=Main] a").allInnerTexts()).join(","), "| home:", await q.locator("h1").first().textContent(), "| talks listed:", await q.locator("main ul li").count());
  await q.screenshot({ path: `${OUT}/e-employee-home.png`, fullPage: true });
  await viewAs("owner");
  log("10 back to owner tabs:", (await q.locator("nav[aria-label=Main] a").allInnerTexts()).join(","));
  // Scenario 11: training cards. Foreman needs a forklift card; add one expiring soon; Home and the profile show it.
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Training')"); await q.waitForTimeout(600);
  await q.selectOption('section[aria-label="What each job title needs"] select', { label: "Foreman" }); await q.waitForTimeout(200);
  await q.locator('input[aria-label="Foreman needs Forklift operator evaluation"]').check(); await q.waitForTimeout(500);
  log("11 summary:", (await q.locator("main p.tabular-nums").first().innerText()).replace(/\s+/g, " "));
  await q.locator("button[aria-label='Training for Example Lead Alvarez']").click(); await q.waitForTimeout(400);
  log("11 sheet before:", (await q.locator("[role=dialog] ul li").first().innerText()).replace(/\s+/g, " "), "| rule note:", (await q.locator("[role=dialog]").innerText()).includes("29 CFR 1910.178"));
  const soon = new Date(Date.now() + 20 * 86400e3).toISOString().slice(0, 10);
  await q.fill("#ct-issued", "2024-01-15"); await q.fill("#ct-expires", soon); await q.click("button:has-text('Save card')"); await q.waitForTimeout(800);
  log("11 sheet after:", (await q.locator("[role=dialog] ul li").first().innerText()).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-training-sheet.png`, fullPage: true });
  await q.click("[role=dialog] button[aria-label=Close]"); await q.waitForTimeout(300);
  await q.screenshot({ path: `${OUT}/e-training.png`, fullPage: true });
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Home"); await q.waitForTimeout(1200);
  log("11 home alert:", (await q.locator("text=Training cards:").first().locator("..").innerText().catch(() => "none")).replace(/\s+/g, " "));
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(900); await q.locator("a[href*='profile']").first().click(); await q.waitForTimeout(1500);
  log("11 profile training:", (await q.locator("li:has-text('Safety training')").first().innerText()).replace(/\s+/g, " ").slice(0, 220));
  // Scenario 12: share with your agent. Make a 30-day link, check what the agent sees, switch it off.
  await q.fill("#share-label", "Example agent"); await q.click("button:has-text('Make private link')"); await q.waitForTimeout(800);
  const link = (await q.locator("p.font-mono").innerText()).trim();
  log("12 link:", link.replace(/#.*/, "#<secret>"), "| secret after #:", /\/share\/#[0-9a-f]{64}$/.test(link));
  await q.screenshot({ path: `${OUT}/e-share-made.png`, fullPage: true });
  await q.click("text=See what they'll see"); await q.waitForTimeout(1500);
  const shared = await q.locator("main").innerText();
  log("12 shared page:", await q.locator("h1").textContent(), "| prepared for:", shared.includes("Prepared for Example agent"), "| no worker names:", !/Alvarez|Example Lead/.test(shared), "| no compliance claim:", !/\bcompliant\b/i.test(shared.replace("doesn't certify compliance", "")));
  await q.screenshot({ path: `${OUT}/e-share-page.png`, fullPage: true });
  await q.evaluate(() => { window.__saved = null; });
  await q.click("button:has-text('Download PDF')"); await q.waitForTimeout(2500);
  log("12 shared pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  await q.goBack().catch(() => {}); await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(900); await q.locator("a[href*='profile']").first().click(); await q.waitForTimeout(1500);
  const row = q.locator("ul[aria-label=\"Links you've made\"] li").first();
  log("12 list:", (await row.innerText()).replace(/\s+/g, " "));
  await row.locator("button:has-text('Switch off')").click(); await row.locator("button:has-text('Tap again')").click(); await q.waitForTimeout(800);
  log("12 after switch off:", (await q.locator("ul[aria-label=\"Links you've made\"] li").first().innerText()).replace(/\s+/g, " "));
  // Scenario 13: trainer portal. Invite a trainer, view as the trainer, send a card, then approve it as the owner.
  await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Training')"); await q.waitForTimeout(800);
  await q.fill("#tr-name", "Example Training Co"); await q.fill("#tr-email", "coach@training.example"); await q.click("button:has-text('Invite trainer')"); await q.waitForTimeout(700);
  log("13 invited:", (await q.locator("section[aria-label=Trainers] ul li").first().innerText()).replace(/\s+/g, " ").slice(0, 120));
  await q.screenshot({ path: `${OUT}/e-trainers-admin.png`, fullPage: true });
  await viewAs("trainer"); await q.waitForTimeout(800);
  log("13 trainer portal:", await q.locator("h1").first().textContent(), "| people:", await q.locator("button[aria-label^='Send a card for']").count(), "| tabs:", await q.locator("nav[aria-label=Main] a").count());
  const who = (await q.locator("button[aria-label^='Send a card for'] b").first().innerText()).trim();
  await q.locator("button[aria-label^='Send a card for']").first().click(); await q.waitForTimeout(400);
  await q.selectOption("#ct-type", "first_aid").catch(() => q.selectOption("#ct-type", { index: 2 }));
  await q.fill("#ct-issued", "2026-09-01"); await q.fill("#ct-expires", "2028-09-01"); await q.click("button:has-text('Send for approval')"); await q.waitForTimeout(800);
  await q.click("[role=dialog] button[aria-label=Close]"); await q.waitForTimeout(300);
  log("13 sent:", (await q.locator("section[aria-label='Cards you sent'] li").first().innerText()).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-trainer-portal.png`, fullPage: true });
  await viewAs("owner"); await q.waitForTimeout(600);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Training')"); await q.waitForTimeout(900);
  log("13 waiting for owner:", (await q.locator("ul[aria-label='Cards waiting for approval'] li").first().innerText()).replace(/\s+/g, " ").slice(0, 160));
  await q.click("ul[aria-label='Cards waiting for approval'] button:has-text('Approve')"); await q.waitForTimeout(900);
  log("13 after approve: waiting", await q.locator("ul[aria-label='Cards waiting for approval'] li").count(), "| card on file:", (await q.locator(`button[aria-label='Training for ${who}']`).innerText()).replace(/\s+/g, " "));
  // Scenario 14: insurance partner portal (pilot). Invite an agent, send the summary, read it as the agent, see the
  // open logged, withdraw it.
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(900); await q.locator("a[href*='profile']").first().click(); await q.waitForTimeout(1500);
  log("14 pilot label:", await q.locator("section[aria-label='Insurance partners'] >> text=Pilot").count() > 0);
  await q.fill("#pt-name", "Example Insurance Agency"); await q.fill("#pt-email", "agent@insure.example"); await q.selectOption("#pt-kind", "agent");
  await q.click("button:has-text('Invite partner')"); await q.waitForTimeout(700);
  await q.click("section[aria-label='Insurance partners'] button:has-text('Send this summary')"); await q.waitForTimeout(800);
  log("14 sent:", (await q.locator("ul[aria-label='Sent to Example Insurance Agency'] li").first().innerText()).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-partners-company.png`, fullPage: true });
  await viewAs("partner"); await q.waitForTimeout(800);
  log("14 partner portal:", await q.locator("h1").first().textContent(), "| summaries:", await q.locator("button[aria-label^='Open summary']").count(), "| tabs:", await q.locator("nav[aria-label=Main] a").count());
  await q.screenshot({ path: `${OUT}/e-partner-inbox.png`, fullPage: true });
  await q.locator("button[aria-label^='Open summary']").first().click(); await q.waitForTimeout(1000);
  const ptext = await q.locator("main").innerText();
  log("14 partner report:", await q.locator("h1").first().textContent(), "| no worker names:", !/Alvarez|Brooks|Diaz/.test(ptext), "| no compliance claim:", !/\bcompliant\b/i.test(ptext.replace("doesn't certify compliance", "")));
  await q.screenshot({ path: `${OUT}/e-partner-report.png`, fullPage: true });
  await viewAs("owner"); await q.waitForTimeout(600);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Reports"); await q.waitForTimeout(900); await q.locator("a[href*='profile']").first().click(); await q.waitForTimeout(1500);
  const sentRow = q.locator("ul[aria-label='Sent to Example Insurance Agency'] li").first();
  log("14 open logged:", (await sentRow.innerText()).replace(/\s+/g, " "));
  await sentRow.locator("button:has-text('Withdraw')").click(); await sentRow.locator("button:has-text('Tap again')").click(); await q.waitForTimeout(800);
  log("14 withdrawn:", (await q.locator("ul[aria-label='Sent to Example Insurance Agency'] li").first().innerText()).replace(/\s+/g, " "));
  // Scenario 15: your own talks. Write one, add checked Spanish as version 2, find it in the Plan's week swap, give it.
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Talks')"); await q.waitForTimeout(500);
  await q.click("main button:has-text('Write a talk')"); await q.waitForTimeout(300);
  const sheet = q.locator("[role=dialog]");
  await sheet.locator("button:has-text('Save talk')").click(); await q.waitForTimeout(200);
  log("15 empty save:", (await sheet.locator("[role=alert], [role=status]").allInnerTexts()).join(" | "));
  await q.fill("#en-title", "Client site rules: Example Hospital"); await q.fill("#en-hook", "This client stops the job for one missed badge.");
  await q.fill("[aria-label='Section 1 heading']", "Before you go in"); await q.fill("[aria-label='Section 1 points, one per line']", "Badge on and visible\nSign in at the dock office\n\nNo work above ceilings without a permit");
  await q.fill("#en-ask", "Who still needs a badge this week?");
  await q.screenshot({ path: `${OUT}/e-own-talk-editor.png`, fullPage: false });
  await sheet.locator("button:has-text('Save talk')").click(); await q.waitForTimeout(800);
  const ownRow = q.locator("main li:has-text('Client site rules')").first();
  log("15 saved:", (await ownRow.innerText()).replace(/\s+/g, " "));
  await ownRow.locator("button:has-text('Edit')").click(); await q.waitForTimeout(300);
  await sheet.locator("[role=tab]:has-text('Spanish')").click(); await sheet.locator("button:has-text('Add Spanish')").click();
  await q.fill("#es-title", "Reglas del cliente: Example Hospital");
  await sheet.locator("button:has-text('Save as version 2')").click(); await q.waitForTimeout(200);
  log("15 half-done Spanish:", (await sheet.locator("[role=alert], [role=status]").allInnerTexts()).join(" | "));
  await q.fill("#es-hook", "Este cliente para el trabajo por un gafete que falte."); await q.fill("#es-ask", "¿Quién necesita gafete esta semana?");
  await q.fill("[aria-label='Section 1 heading']", "Antes de entrar"); await q.fill("[aria-label='Section 1 points, one per line']", "Gafete puesto y visible");
  await q.screenshot({ path: `${OUT}/e-own-talk-spanish.png`, fullPage: false });
  await sheet.locator("input[type=checkbox]").check(); await sheet.locator("button:has-text('Save as version 2')").click(); await q.waitForTimeout(200);
  log("15 no reviewer:", (await sheet.locator("[role=alert], [role=status]").allInnerTexts()).join(" | "));
  await q.fill("#own-reviewer", "Example Reviewer"); await sheet.locator("button:has-text('Save as version 2')").click(); await q.waitForTimeout(800);
  log("15 version 2:", (await ownRow.innerText()).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-own-talks.png`, fullPage: false });
  log("15 in the picker:", await q.locator("main section:has(h2:has-text('Your own talks')) label:has-text('Client site rules')").count() + await q.locator("main label:has-text('Client site rules')").count());
  await q.click("[role=tab]:has-text('Plan')"); await q.waitForTimeout(600);
  log("15 week swap offers it:", await q.locator("main li select").first().locator("optgroup[label='Your own talks'] option", { hasText: "Client site rules" }).count());
  await q.click("[role=tab]:has-text('Talks')"); await q.waitForTimeout(400);
  await q.locator("main li:has-text('Client site rules') button:has-text('Give it now')").click(); await q.waitForTimeout(1200);
  log("15 giving:", await q.locator("main h1, main h2").first().textContent(), "| sections:", (await q.locator("main").innerText()).includes("Sign in at the dock office"));
  await q.screenshot({ path: `${OUT}/e-own-talk-give.png`, fullPage: false });
  // Scenario 15b: tailor a library talk with AI (the preview's example draft), check it, save it as AI-drafted.
  await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Talks')"); await q.waitForTimeout(500);
  const ai = q.locator("section[aria-label='Tailor with AI']");
  await ai.locator("select").selectOption("ladder"); await ai.locator("textarea").fill("Two-story reroofs, ladders set on soft yards");
  await ai.locator("button:has-text('Draft it')").click(); await q.waitForTimeout(1200);
  log("15b ai notice:", (await q.locator("[role=dialog] [role=status]").first().innerText()).replace(/\s+/g, " ").slice(0, 90));
  await q.locator("[role=dialog] button:has-text('Save talk')").click(); await q.waitForTimeout(800);
  log("15b saved:", await q.locator("main li:has-text('example AI draft')").count());
  // Scenario 16: check a record from its PDF. The record shows its check code; the QR link opens /verify with counts
  // and no names; a mistyped code finds nothing.
  await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Records"); await q.waitForTimeout(800);
  await q.locator("main a[href*='record']").first().click(); await q.waitForTimeout(1200);
  const code = (await q.locator("dt:has-text('Check code') + dd").innerText()).trim();
  log("16 record code:", /^[2-9A-HJKMNP-Z]{4}(-[2-9A-HJKMNP-Z]{4}){3}$/.test(code));
  await q.evaluate((c) => { sessionStorage.setItem("tt-preview-start", "/verify/"); location.hash = c.replace(/-/g, ""); }, code);
  await q.reload(); await q.waitForTimeout(1500);
  const vtext = await q.locator("main").innerText();
  log("16 verify:", await q.locator("h1").first().textContent(), "| found:", vtext.includes("on file"), "|", (await q.locator("section[aria-label='What was saved'] p.text-sm").first().innerText()),
    "| no worker names:", !/Alvarez|Brooks|Diaz|Example Lead|Example Worker/.test(vtext), "| no compliance claim:", !/\bcompliant\b/i.test(vtext));
  await q.screenshot({ path: `${OUT}/e-verify.png`, fullPage: true });
  await q.fill("input[aria-label='Check code']", code.slice(0, -1) + (code.endsWith("2") ? "3" : "2")); await q.click("button:has-text('Check')"); await q.waitForTimeout(800);
  log("16 mistyped:", (await q.locator("main [role=status], main [role=alert]").allInnerTexts()).map((t) => t.replace(/\s+/g, " ")).join(" | "));
  await q.goto(PAGE); await q.waitForTimeout(800);
  // Scenario 17: OSHA 300 log. Add a days-away case for someone on the list and a privacy case, see the totals and
  // rates, fill the 300A details, download the log and the summary.
  await q.click("nav:is([aria-label=Main],[aria-label=Menu]):visible >> text=Admin"); await q.waitForTimeout(600); await q.click("[role=tab]:has-text('Injury log')"); await q.waitForTimeout(700);
  const isheet = q.locator("[role=dialog]");
  await q.click("main button:has-text('Add a case')"); await q.waitForTimeout(300);
  const firstPerson = await q.locator("#inj-person option").nth(1).getAttribute("value");
  await q.selectOption("#inj-person", firstPerson);
  await q.fill("#inj-date", `${new Date().getFullYear()}-03-02`); await q.fill("#inj-where", "Example Jobsite, north roof");
  await q.fill("#inj-desc", "Sprained left ankle stepping off a ladder onto uneven decking");
  await isheet.locator("label:has-text('(H) Days away from work')").click(); await q.fill("#inj-away", "0");
  await isheet.locator("button:has-text('Add to the log')").click(); await q.waitForTimeout(200);
  log("17 zero days:", (await isheet.locator("[role=alert]").allInnerTexts()).join(" | "));
  await q.fill("#inj-away", "3");
  await q.fill("#inj-dob", "1990-01-15"); await q.fill("#inj-hired", "2024-05-01");
  await isheet.locator("fieldset:has-text('emergency room') label:has-text('No')").click(); await isheet.locator("fieldset:has-text('in-patient') label:has-text('No')").click();
  await q.fill("#inj-time", "09:30"); await q.fill("#inj-activity_before", "Carrying a bundle of shingles down a ladder");
  await q.fill("#inj-what_happened", "Example Diaz missed the last rung"); await q.fill("#inj-injury_detail", "Sprained left ankle"); await q.fill("#inj-object_substance", "Ladder rung");
  log("17 name warning:", (await isheet.locator("[role=status]:has-text('Leave names out')").count()) > 0);
  await q.fill("#inj-what_happened", "Missed the last rung and landed on uneven decking");
  await q.screenshot({ path: `${OUT}/e-injury-editor.png`, fullPage: false });
  await isheet.locator("button:has-text('Add to the log')").click(); await q.waitForTimeout(800);
  await q.click("main button:has-text('Add a case')"); await q.waitForTimeout(300);
  await q.fill("#inj-name", "Example Private Person"); await q.fill("#inj-date", `${new Date().getFullYear()}-05-14`);
  await q.fill("#inj-desc", "Skin rash on both hands from adhesive"); await q.selectOption("#inj-kind", "skin");
  await isheet.locator("label:has-text('Privacy case.') input[type=checkbox]").check(); await q.selectOption("#inj-why", "employee_request");
  await isheet.locator("button:has-text('Add to the log')").click(); await q.waitForTimeout(800);
  log("17 cases:", (await q.locator("main ul li b").allInnerTexts()).filter((t) => /^\d{4}-\d{3}/.test(t)).join(" | "));
  await q.fill("#sum-avg", "24"); await q.fill("#sum-hours", "49920"); await q.fill("#sum-naics", "238160");
  await q.fill("#sum-street", "1 Example St"); await q.fill("#sum-city", "Fort Myers"); await q.fill("#sum-state", "FL"); await q.fill("#sum-zip", "33913");
  await q.fill("#sum-ein", "123456789"); await q.fill("#sum-peak", "31");
  await q.click("main button:has-text('Save summary details')"); await q.waitForTimeout(800);
  log("17 totals:", (await q.locator("main p:has-text('days away ·')").first().innerText()).replace(/\s+/g, " "));
  await q.screenshot({ path: `${OUT}/e-injury-log.png`, fullPage: true });
  log("17 filing:", (await q.locator("section[aria-label='Filing online with OSHA'] p.font-semibold").innerText()));
  for (const label of ["log (300) PDF", "summary (300A) PDF", "Privacy case list", "300A file for OSHA"]) {
    await q.evaluate(() => { window.__saved = null; });
    await q.locator(`main button:has-text("${label}")`).click(); await q.waitForTimeout(1500);
    log(`17 ${label}:`, JSON.stringify(await q.evaluate(() => window.__saved)));
  }
  // Scenario 17b: a second OSHA log for a location (1904.30). Start it, add a case there, see each log keep its own.
  await q.click("main button:has-text('More than one location')"); await q.waitForTimeout(200);
  await q.fill("#est-name", "North yard"); await q.click("main button:has-text('Start this log')"); await q.waitForTimeout(800);
  log("17b picker:", await q.locator("#osha-log option:checked").innerText(), "| empty:", await q.locator("main p:has-text('No recordable cases')").count() > 0);
  await q.click("main button:has-text('Add a case to North yard')"); await q.waitForTimeout(300);
  await q.fill("#inj-name", "Example Yard Worker"); await q.fill("#inj-date", `${new Date().getFullYear()}-06-03`); await q.fill("#inj-desc", "Cut on left hand from sheet metal");
  await isheet.locator("button:has-text('Add to the log')").click(); await q.waitForTimeout(800);
  const yardCases = (await q.locator("main ul li b").allInnerTexts()).filter((t) => /^\d{4}-\d{3}/.test(t));
  await q.evaluate(() => { window.__saved = null; });
  await q.locator('main button:has-text("log (300) PDF")').click(); await q.waitForTimeout(1500);
  log("17b yard log:", yardCases.join(" | "), "| file:", JSON.stringify(await q.evaluate(() => window.__saved)));
  // This location's own 300A saves even though the main log already has a 2026 summary (versions count company-wide).
  await q.fill("#sum-peak", "40"); await q.fill("#sum-naics", "238160");
  await q.click("main button:has-text('Save summary details')"); await q.waitForTimeout(800);
  log("17b yard 300A:", await q.evaluate(() => JSON.stringify((JSON.parse(localStorage.getItem("tt-preview-db") || "{}").injurySummaries ?? []).map((x) => [x.version, x.establishment_id ? "yard" : "main", x.peak_employees]))),
    "| filing:", await q.locator("section[aria-label='Filing online with OSHA'] p.font-semibold").innerText());
  await q.locator("#osha-log").scrollIntoViewIfNeeded(); await q.evaluate(() => window.scrollBy(0, -120));
  await q.screenshot({ path: `${OUT}/e-injury-locations.png`, fullPage: false });
  await q.selectOption("#osha-log", ""); await q.waitForTimeout(300);
  log("17b main log:", (await q.locator("main ul li b").allInnerTexts()).filter((t) => /^\d{4}-\d{3}/.test(t)).join(" | "));
  // Scenario 18: inspections. Home card, run the ladder checklist with one failure (note + issue), sign, save, see it in
  // Recent, open it, download the PDF, then check it on /verify by its code.
  await q.goto(PAGE); await q.waitForTimeout(1200);
  log("18 home card:", (await q.locator("a[href*='inspect']").first().innerText()).replace(/\s+/g, " "));
  await q.locator("a[href*='inspect']").first().click(); await q.waitForTimeout(1000);
  log("18 lists:", await q.locator("main li:has(button[aria-label^='Start'])").count(), "| groups:", (await q.locator("main h2").allTextContents()).join(", "));
  await q.screenshot({ path: `${OUT}/e-inspect-list.png`, fullPage: false });
  await q.click("button[aria-label='Start Ladders']"); await q.waitForTimeout(700);
  await q.fill("#insp-subject", "24 ft extension ladder");
  await q.click("[aria-label='Result for item 1'] >> text=Fail");
  await q.click("main button:has-text('Save inspection'), main button:has-text('Mark every item')"); await q.waitForTimeout(200);
  log("18 blank:", (await q.locator("main [role=alert]").allInnerTexts()).join(" | "));
  await q.click("main button:has-text('Mark the rest as pass')");
  await q.fill("[aria-label=\"What's wrong with item 1\"]", "Cracked right rail near the third rung");
  await q.selectOption("#insp-by", { index: 1 });
  const pad = q.locator("canvas").first(); await pad.scrollIntoViewIfNeeded(); const box = await pad.boundingBox();
  await q.mouse.move(box.x + 20, box.y + 40); await q.mouse.down(); await q.mouse.move(box.x + 160, box.y + 60, { steps: 8 }); await q.mouse.move(box.x + 60, box.y + 20, { steps: 8 }); await q.mouse.up();
  await q.screenshot({ path: `${OUT}/e-inspect-run.png`, fullPage: false });
  await q.click("main button:has-text('Save inspection')"); await q.waitForTimeout(1200);
  log("18 save message:", (await q.locator("main [role=alert]").allInnerTexts()).join(" | ") || "none");
  log("18 saved:", (await q.locator("main").innerText()).replace(/\s+/g, " ").slice(0, 160));
  await q.click("main button:has-text('Back to inspections')"); await q.waitForTimeout(900);
  const recent = q.locator("main button[aria-label^='Open Ladders']").first();
  log("18 recent:", (await recent.innerText()).replace(/\s+/g, " "));
  await recent.click(); await q.waitForTimeout(900);
  await q.evaluate(() => { window.__saved = null; });
  await q.click("main button:has-text('Download PDF')"); await q.waitForTimeout(1500);
  log("18 pdf:", JSON.stringify(await q.evaluate(() => window.__saved)));
  const inspCode = await q.evaluate(() => { const d = JSON.parse(localStorage.getItem("tt-preview-db") || "{}"); return (d.inspections ?? []).at(-1)?.verify_code ?? null; });
  if (inspCode) {
    await q.evaluate((c) => { sessionStorage.setItem("tt-preview-start", "/verify/"); location.hash = c; }, inspCode);
    await q.reload(); await q.waitForTimeout(1500);
    log("18 verify:", (await q.locator("section[aria-label='What was saved']").innerText()).replace(/\s+/g, " ").slice(0, 140));
    log("18 wording:", (await q.locator("section[aria-label='What was saved'] p:has-text('checklist')").allInnerTexts()).join(" | ") || "no wording line");
  } else log("18 verify: no code found in demo store");
  // Scenario 19: My record. Home card opens the signed-in person's own record: stats, what's owed, no rankings.
  await q.goto(PAGE); await q.waitForTimeout(1000);
  await q.click("main a[href*='/me']"); await q.waitForTimeout(1000);
  const me = (await q.locator("main").innerText()).replace(/\s+/g, " ");
  log("19 my record:", await q.locator("h1").first().textContent(), "|", me.slice(0, 220), "| no ranking words:", !/\b(rank|leaderboard|top performer)\b/i.test(me.replace("no rankings", "")));
  await q.screenshot({ path: `${OUT}/e-my-record.png`, fullPage: true });
  await q.goto(PAGE); await q.waitForTimeout(800);
  log("errors:", errs.length ? errs : "none");
  await b.close();
  if (errs.length) process.exit(1);
})().catch((e) => { console.log("E2E ERROR", e.message.split("\n")[0]); process.exit(1); });
